### ISSUE TITLE
[Wiki Revision] Update System Requirements

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#100]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [System Requirements](https://github.com/bounswe/bounswe2024group2/wiki/Requirements#12-system-requirements)

### Required Changes

- Revise necessary requirements and make changes according to the feedback of the assistant.

### Acceptance Criteria

- [x] Changes are made and visible
- [ ] Changes are reviewed by the reviewer

### Reviewer

@Halil-Ibrahim-Kasapoglu

### Deadline

28 April 2024

**Comment by furkansenkal** [comment]
I revised and updated the system requirements according to the feedback of the assistant. You can see the new version of system requirements from [here](https://github.com/bounswe/bounswe2024group2/wiki/Requirements#12-system-requirements).

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I think they are fine well done. Closing the issue.
