### ISSUE TITLE
[Wiki Revision] Update User Scenarios

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#102]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [User Scenarios](https://github.com/bounswe/bounswe2024group2/wiki/User-Scenarios)

### Required Changes

- Address requirements to the user scenarios.
- Support scenarios with the mock-ups and indicate which mock-ups belong to which scenario.

### Acceptance Criteria

- [x] Changes are made and visible
- [x] Changes are reviewed by the reviewer

### Reviewer

@Halil-Ibrahim-Kasapoglu

### Deadline

21 April 2024

**Comment by yasinbastug** [comment]
I updated 2nd and 3rd scenarios accordingly.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Good job team. I have reviewed your work and it looks really good. Closing the issue.
