### ISSUE TITLE
[Wiki Revision] Revise Project Plan

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#103]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [Project Plan](https://github.com/bounswe/bounswe2024group2/wiki/Project-Plan)

### Required Changes

- Add some missing tasks to the project plan.

### Acceptance Criteria

- [x] Changes are made and visible
- [x] Changes are reviewed by the reviewer

### Reviewer

@m-erkam

### Deadline

21 April 2024

**Comment by mahmutbugramert** [comment]
Project plan wiki page is updated. See [here](https://github.com/bounswe/bounswe2024group2/wiki/Project-Plan).

**Comment by mahmutbugramert** [comment]
Project plan .pod and .pdf filesare updated. See [here](https://github.com/bounswe/bounswe2024group2/commit/f3d973921cbd7d6bbb88d916f8887eed757a6f05).

**Comment by mahmutbugramert** [comment]
Use case, and Class diagrams will be added to the Project Plan wiki page once their wiki page is finalized. Need review of @m-erkam

**Comment by mahmutbugramert** [comment]
Deployment part of project plan is changed after review of @rukiyeaslan. See [here](https://github.com/bounswe/bounswe2024group2/commit/b81c1a550b39892651faa5b4ad8e16dda7613f51).

**Comment by rukiyeaslan** [comment]
Project plan is reviewed and requested changes are nicely done, so closing the issue. Good job!
