### ISSUE TITLE
Add Meeting Notes 10

### ISSUE THREAD

**Issue by iremnuy** [bounswe/bounswe2024group2#104]
### Meeting Details

- Meeting 10
- Date: 18.04.2024
- Note Taker: @iremnuy 
- Wiki-Documenter: @Halil-Ibrahim-Kasapoglu 
- Platform: Discord

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Reviewer

@mahmutbugramert

### Deadline

19 April 2024

**Comment by iremnuy** [comment]
Shared meeting notes on discord

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Added the notes to the wiki and linked it in the sidebar. The page is [here](https://github.com/bounswe/bounswe2024group2/wiki/10th-Meeting,18.04.2024).

You can review and close the issue afterward @mahmutbugramert
