### ISSUE TITLE
Create sequence diagram 

### ISSUE THREAD

**Issue by iremnuy** [bounswe/bounswe2024group2#106]
Sequence diagrams for the project should be created and uploaded to Sequence Diagrams page in wiki.

Reviewer: @Halil-Ibrahim-Kasapoglu
Deadline: 30 April, 2024

**Comment by rukiyeaslan** [comment]
The plan for the sequence diagram is prepared and diagrams for the following sections below will be prepared:

**Guest**

- register

**Registered User**

- login
- logout
- rate film
- bookmark post
- create post
- like posts
- write comments to the posts
- follow/unfollow user
- view followers
- view following users
- create list

**Admin**

- login
- logout
- delete film list
- ban registered user accounts
- remove posts
- remove comments on posts

**User**

- search film 
- view film
- view user profiles
- view post
- view film lists

**Comment by rukiyeaslan** [comment]
Added sequence diagrams for guest and registered user. Changes can be accessed from [here](https://github.com/bounswe/bounswe2024group2/wiki/Sequence-Diagrams/23041ed126f38f6182e7656ef757c7fcf6b5d5a5).

**Comment by yasinbastug** [comment]
Added sequence diagrams for admin. Changes can be accessed from [here](https://github.com/bounswe/bounswe2024group2/wiki/Sequence-Diagrams/bc25965be74ca8077b4ba2959aa78fae08f2808b).

**Comment by mahmutbugramert** [comment]
Added sequence diagrams for user. Changes can be accessed from [here](https://github.com/bounswe/bounswe2024group2/wiki/Sequence-Diagrams/cb87fc3a20c573eb46d043403e861d5869b89334).

**Comment by rukiyeaslan** [comment]
The tasks for this issue are completed and can ve reviewed @Halil-Ibrahim-Kasapoglu.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Looks good to me. Closing the issue.
