### ISSUE TITLE
Create Film Model and Film Endpoints

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#122]
### Description

Models for Film should be implemented and get, post, delete, put endpoints for Film model should be implemented

### Acceptance Criteria

- [ ] Materials are consumed

### Deadline

30 April, 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
It seems the crud operations for Films are implemented. Is this issue completed or are you still working on it @rukiyeaslan ?

**Comment by rukiyeaslan** [comment]
> It seems the crud operations for Films are implemented. Is this issue completed or are you still working on it @rukiyeaslan ?

Yes, the task is completed and ready for a review @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Nicely done. I am closing the issue.
