### ISSUE TITLE
Add Email Verification for Signup

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#123]
### Description

Since a user will signup using her/his email, an email verification mechanism should be implemented in backend.

### Acceptance Criteria

- [x] Materials are consumed

### Deadline

30 April, 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
SMTP config works well. Good job. Closing the issue.
