### ISSUE TITLE
Create Forgot Password Page

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#129]
### Description

A forgot password page should be created for web and be linked with backend.

### Required Activities

* [x] Create forgot password page
* [ ] Link page with backend

### Estimated Time

4 hours

### Deadline

30.04.2024

### Reviewer

@yasinbastug

**Comment by mahmutbugramert** [comment]
Forgot password page is created. It will be linked with backend.

**Comment by yasinbastug** [comment]
It seems to be done. Good job!
