### ISSUE TITLE
[Wiki Revision] Update Readme for Quickstart

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#133]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [Readme](https://github.com/bounswe/bounswe2024group2?tab=readme-ov-file#)
- [Wiki Home](https://github.com/bounswe/bounswe2024group2/wiki)

### Required Changes

- We should create sections in the readme and wiki home page that describe instructions for running the application. Give detailed docker commands and any other to how to get docker images and run containers. Also, describe how/where to access running applications after containers are up and running.

### Acceptance Criteria

- [x] Changes are made and visible
- [x] Changes are reviewed by the reviewer

### Reviewer

@rukiyeaslan 

### Deadline

30 April 2024

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have created readme sections for the installation guide and prerequisites.See [here](https://github.com/bounswe/bounswe2024group2?tab=readme-ov-file#installation) for readme. For the wiki, one can see the quickstart guide placed at the footer. See [here](https://github.com/bounswe/bounswe2024group2/wiki/Quickstart)

Up for review before closing this one.

**Comment by rukiyeaslan** [comment]
Reviewed the quickstart on wiki and looks nice so the task is completed.
