### ISSUE TITLE
Connect Login and Signup Pages of the Mobile App to the Backend

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#134]
### Description

Login and signup pages are created. The backend part about login  is also created. The connection between them should be done. 

### Required Activities

- Link login page with the backend
- Link signup page with the backend

### Acceptance Criteria

Pages are linked to the backend and work properly.

### Estimated Time

2

### Deadline

30 April 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Login and signup pages are linked to the backend and now the app can be able to make authantication.

**Comment by furkansenkal** [comment]
I reviewed your work and it is working good. Well done!
