### ISSUE TITLE
Add Container Settings For Web

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#135]
Web application should be deployed and the container should be up and running at the Digital Ocean droplet. To do so we should update our docker-compose file and write a respective Dockerfile for web.

### Acceptance Criteria
- [x] Web application can be dockerized via docker-compose

### Reviewer
@iremnuy   

### Deadline
30 April 2024

**Comment by iremnuy** [comment]
You can add frontend service to our existing docker-compose.yml file in backend/project folder that must be enough

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
[Solved](https://github.com/bounswe/bounswe2024group2/commit/b7348959dd1974ca562deef1bf4067c132900d7f). Issue is up for review @iremnuy

**Comment by iremnuy** [comment]
seems ok, great work !!
