### ISSUE TITLE
Create Main Page of Mobile App

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#141]
### Description

Create search bar, recent activities section, popular movies slider and navigation bar in main page for mobile app.

### Required Activities

- [x] - Create Search Bar
- [x] - Create Recent Activities Section
- [x] - Create Popular Movies Slider

### Acceptance Criteria

- [x] Materials are consumed

### Estimated Time

5

### Deadline

30 April 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
Main page initialized except navigation bar.

**Comment by m-erkam** [comment]
Reviewed the work. Main page is initialized and working nice with mock data. Well done!
