### ISSUE TITLE
Fix Cors Error

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#144]
There exist an issue for frontend to send rest requests to backend since we have not configured the cors settings correctly. It needs to be fixed.

`Access to fetch at 'http://207.154.242.6:8020/register/' from origin 'http://207.154.242.6:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

### Reviewer 
@mahmutbugramert 

### Deadline 
30 April 2024

**Comment by rukiyeaslan** [comment]
Required changes are made so the branch is merged. The task is ready for a review @mahmutbugramert.

**Comment by mahmutbugramert** [comment]
Issue seems solved. Well done!
