### ISSUE TITLE
Fix Login information in frontend

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#146]
Login information is not hold in frontend. After refreshing page main page appears as default. Review the code and make login saved. 

### Acceptance Criteria
The code is fixed and login works properly

### Reviewer
@Halil-Ibrahim-Kasapoglu 

### Deadline 
30 April 2024

**Comment by mahmutbugramert** [comment]
Issue is solved after @yasinbastug's changes. Hence issue can be closed after reviews of @Halil-Ibrahim-Kasapoglu.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have tested and it works. Well done. Closing the issue.
