### ISSUE TITLE
Create the Profile Page of Mobile App

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#150]
### Description

Search page should be created for demo using mock data.

### Required Activities

- [x] - Create Profile Page

### Acceptance Criteria

- [x] Materials are consumed

### Estimated Time

2

### Deadline

30 April 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
Profile page is initialized.

**Comment by m-erkam** [comment]
Reviewed the work. The profile page is implemented appropriately and working well. Good work!
