### ISSUE TITLE
Create Main Page (Frontend)

### ISSUE THREAD

**Issue by yasinbastug** [bounswe/bounswe2024group2#159]
### Description

Create main page with film list bars.

### Required Activities
* [x] Create main page.
* [x] Link main page with other pages

### Estimated Time

5

### Deadline

30.04.2024

### Reviewer

@mahmutbugramert

**Comment by yasinbastug** [comment]
It is done. [https://github.com/bounswe/bounswe2024group2/pull/110](commits)
Maybe review it @mahmutbugramert

**Comment by mahmutbugramert** [comment]
Main page is created and works fine. Well done!
