### ISSUE TITLE
Create a search bar for the navigation bar

### ISSUE THREAD

**Issue by yasinbastug** [bounswe/bounswe2024group2#161]
### Description

A search bar that calls the pattern endpoint and fetchs 5 matching films needs to be implemented.

### Acceptance Criteria

- [x] #162

### Estimated Time

2

### Deadline

30.04.2024

### Reviewer

@mahmutbugramert

**Comment by yasinbastug** [comment]
[https://github.com/bounswe/bounswe2024group2/pull/154](done)

**Comment by mahmutbugramert** [comment]
Initial search bar is done and properly working. In future it may need improvements. Well Done!
