### ISSUE TITLE
Add Meeting Notes 12

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#165]
### Meeting Details

- Meeting 12
- Date: 02.05.2024
- Note Taker: @mahmutbugramert
- Wiki-Documenter: @rukiyeaslan 
- Platform: Discord

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Reviewer

@iremnuy

### Deadline

05 May 2024

**Comment by mahmutbugramert** [comment]
Notes are shared on discord. Ready to upload to the wiki page.

**Comment by rukiyeaslan** [comment]
Wiki page for meeting 12 notes are on wiki and can be accessed from [here](https://github.com/bounswe/bounswe2024group2/wiki/12th-Meeting,02.05.2024/9a29ffd6940a0cbce3c674f3731ce467c77e8386).
This task is ready for review. @iremnuy

**Comment by iremnuy** [comment]
I reviewed the notes and wiki page, thank you!
