### ISSUE TITLE
Add Meeting Notes 11

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#167]
### Meeting Details

- Meeting 11
- Date: 25.04.2024
- Note Taker: @yasinbastug 
- Platform: Discord

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Reviewer

@furkansenkal

### Deadline

3 May 2024

**Comment by m-erkam** [comment]
11th meeting notes are added to the wiki. The shortcut to the page is available on sidebar. Issue can be closed after revision by @furkansenkal

**Comment by furkansenkal** [comment]
I rewieved the meeting notes and everything looks fine, well done! Closing the issue.
