### ISSUE TITLE
Decide on a Branch and Issue Naming Convention

### ISSUE THREAD

**Issue by yasinbastug** [bounswe/bounswe2024group2#168]
### Description

Decide on a branch and issue naming convention for development issues and branches in frontend, backend and mobile. Frontend issues can be opened as "[FE-X] - (Issue Title)" and the branches can be initialized as FE-X-(Developer Name). This way branches can be attached to issues easily and branches won't cause any confusion. BE and MB codes can be used for backend and mobile respectively. 

### Required Activities

- Discuss with team members
- Decision
- An explanation on this in the wiki page

### Estimated Time

1

### Deadline

07 May 2024

### Reviewer

@rukiyeaslan

**Comment by rukiyeaslan** [comment]
The convention is accepted by the team and we've been using this convention when creating pull requests. Task is completed.
