### ISSUE TITLE
Document the meeting notes

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#17]
Meeting 1 notes will be taken by Rukiye Aslan and the notes will be documented on wiki by Irem Nur Yildirim.

- [x] Take the meeting notes.
- [x] Document the notes on wiki

**Comment by rukiyeaslan** [comment]
Meeting notes are taken and sent to Irem to be documented on wiki.

**Comment by iremnuy** [comment]
Documented the notes on [wiki](https://github.com/bounswe/bounswe2024group2/wiki/1st-Meeting)
