### ISSUE TITLE
[FE-12] Update Main Page

### ISSUE THREAD

**Issue by yasinbastug** [bounswe/bounswe2024group2#170]
### Description

Update the Main Page according to the updates in backend. 

### Required Activities

- Add post button
- Update the film and lists bars

### Estimated Time

2

### Deadline

07 May 2024

### Reviewer

@mahmutbugramert

**Comment by yasinbastug** [comment]
i updated it to have posters presented

**Comment by mahmutbugramert** [comment]
New changes are visible. Well done!
