### ISSUE TITLE
[FE-13] Add posting interface

### ISSUE THREAD

**Issue by yasinbastug** [bounswe/bounswe2024group2#171]
### Description

Posting functionality should be added according to the mockups and backend.

### Required Activities

- Add posting interface
- Link to necessary buttons

### Estimated Time

4

### Deadline

12th May 2024

### Reviewer

@mahmutbugramert

**Comment by yasinbastug** [comment]
it is done review pls @mahmutbugramert

**Comment by mahmutbugramert** [comment]
I initialized the page and Yasin linked it with backend. Now it works properly. Great job!
