### ISSUE TITLE
[BE-16] - Implement Create Post Endpoint 

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#172]
### Description

We need to implement post creation functionality in backend where a logged in user will be able to enter:
- title of the post
- a description of the post

### Required Activities

- [ ] Endpoint is visible on swagger and works as described.

### Estimated Time

3

### Deadline

17th May 2024

### Reviewer

@iremnuy

**Comment by iremnuy** [comment]
Works well, thank you!
