### ISSUE TITLE
[MB-8] - Update Profile Page

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#173]
### Description

Profile page should be updated so that the users can see their information and the posts, film lists etc properly.

### Required Activities

- [x] Add profile information to the page
- [x] Make necessary updates to improve the functionality of the page (like update password (optional))

### Estimated Time

3

### Deadline

17 May 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
Profile information and some necessary updates to improve the functionality of the profile page like update password are added to mobile application.

**Comment by m-erkam** [comment]
Profile page is updated and the user posts can be accessable from the profile. Nice work!
