### ISSUE TITLE
[MB-9] - Add Post Creation Functionality to the Mobile

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#174]
### Description

Mobile app should have the post creation feature so it should be implemented. Also, created posts should be stored in the database of the platform.

### Required Activities

- [x] Add create post function to the mobile
- [x] Store the posts in the database of the platform

### Estimated Time

4

### Deadline

17 May 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
In order to create post, the films page should be implemented first and posts can be created through the seperate film pages.

**Comment by m-erkam** [comment]
Posts are now available under the movie pages, and all posts can be seen on the main page (retrieved from our database)

**Comment by furkansenkal** [comment]
I reviewed your work and it is working good. Well done!
