### ISSUE TITLE
[BE-17] - Implement Like Post Functionality

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#175]
### Description

We need to implement like and unlike functionalities for posts in backend.

### Required Activities

- [x] Logged in user can like a post.
- [x] Logged in user can unlike a post.

### Estimated Time

2

### Deadline

17th May 2024

### Reviewer

@iremnuy

**Comment by iremnuy** [comment]
Endpoints work well thank you!
