### ISSUE TITLE
[MB-10] - Update Main Page

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#176]
### Description

The bottom tab should be added to the main page so that films page and profile page can be accessed from there.

### Required Activities

- [x] Add bottom tab to the main page
- [x] Move profile page connection to the tab

### Estimated Time

2

### Deadline

17 May 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Changes are applied to the main page. After the review of the @furkansenkal issue can be closed

**Comment by furkansenkal** [comment]
I reviewed your work and it is working good. Well done!
