### ISSUE TITLE
Implement Wiki search filtering

### ISSUE THREAD

**Issue by iremnuy** [bounswe/bounswe2024group2#177]
### Description

Adjust the searching mechanism with respect to filters : genre,rating,director,actor,movie name.

### Required Activities

- [XX](url)
- [XX](url)

### Estimated Time

17.05.2024

### Deadline

17.05.2024

### Reviewer

@rukiyeaslan

**Comment by rukiyeaslan** [comment]
Search functionality is implemented with filtering, well done.
