### ISSUE TITLE
Update env skeleton before CMS3

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#205]
After a though implementation process, we are now heading for closure. Throughout the dev process our env file skeleton has changed and we should update the instructions for that. 

Current env skeleton looks like the following

```
APP_USER_PASS=
OMDB_API_KEY=
SECRET_KEY=
DEBUG=True
MYSQL_ROOT_PASSWORD=
MYSQL_DATABASE=
DB_NAME=
DB_USER=
DB_PASSWORD=
DB_HOST=
DB_PORT=
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=
TMDB_API_KEY=
TMDB_RATE_LIMIT=
```

Make sure to update readme and deployment guide on wiki. 

### Reviewer
@iremnuy 

### Deadline
17 May 2024

**Comment by rukiyeaslan** [comment]
Requested changes are made on the quickstart page and can be found from [here](https://github.com/bounswe/bounswe2024group2/wiki/Quickstart/042396b95a045928be43ea09417098ce53ec3f60).
This task can be reviewed @iremnuy

**Comment by iremnuy** [comment]
Quickstart page has all required env fields.
