### ISSUE TITLE
Implement Unit Tests for Post

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#207]
### Description

Unit tests for post endpoints needs top be implemented.

### Required Activities

- [x] Tests are implemented
- [x] Tests test the expected responses.

### Estimated Time

1

### Deadline

17th May 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Looks good to me and since its merged I will close this issue.
