### ISSUE TITLE
[MB-12] Add Genre Filter to Films Page

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#210]
### Description

Filter buttons should be created and genre filter should be connected to the relevant backend endpoint.

### Required Activities

- [x] Add Filter Buttons
- [x] Connect Genre Filter to Backend

### Estimated Time

3

### Deadline

17.05.2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
Filter buttons are created, genre filter is connected to the relevant backend endpoint and works without an error.

**Comment by m-erkam** [comment]
Buttons and filter are added and works properly, well done!
