### ISSUE TITLE
[FE-16] Add Film Details Page

### ISSUE THREAD

**Issue by yasinbastug** [bounswe/bounswe2024group2#216]
### Description

A film details page with description is needed.

### Required Activities

- Add film details page with create post button
- Attach to main page and movie containers

### Estimated Time

3

### Deadline

17 May 2024

### Reviewer

@mahmutbugramert

**Comment by yasinbastug** [comment]
it is done pls review

**Comment by mahmutbugramert** [comment]
It works properly. Well done!
