### ISSUE TITLE
[FE-19] Add Authorization to Create Post Functions

### ISSUE THREAD

**Issue by yasinbastug** [bounswe/bounswe2024group2#217]
### Description

Fix the failing creating post feature

### Required Activities

- Save bearer to authorize in the login
- Use it in the post page

### Estimated Time

2

### Deadline

17 May 2024

### Reviewer

@mahmutbugramert

**Comment by yasinbastug** [comment]
done

**Comment by mahmutbugramert** [comment]
It works properly. Well done!
