### ISSUE TITLE
Take Lab Meeting Notes - Week 1

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#219]
### Description

First lab of the semester will be held on 24th Sep, 2024.

### Required Activities

- [x] (Take notes during lab)

- [x] (Document notes to the wiki)

### Estimated Time

2h

### Deadline

24 Sep 2024

### Reviewer

@m-erkam

**Comment by rukiyeaslan** [comment]
Lab notes can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/1st-Lab-Meeting-Report,24.09.2024).
This issue is completed and ready for a review by @m-erkam

**Comment by m-erkam** [comment]
Notes are checked, nice work!
