### ISSUE TITLE
Take Lab Reports - Week 1

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#222]
### Description

Briefly explain what is done during the lab hours and document it. Then, upload lab report to wiki page.

### Required Activities

- [x] Take lab report
- [x] Upload lab report to wiki page

### Estimated Time

2 hours

### Deadline

24/09/2024

### Reviewer

@danzio19

**Comment by mahmutbugramert** [comment]
Report is uploaded to the wiki page. Here is the [link](https://github.com/bounswe/bounswe2024group2/wiki/Lab-Report-%231). Can be reviewed now @danzio19

**Comment by danzio19** [comment]
The requirements are completed and reviewed, hence this issue is closed.
