### ISSUE TITLE
Update Communication Plan

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#224]
### Description

Weekly meeting time has changed and the changes need to be reflected to the wiki page.

### Required Activities

- [x] (Update Communication Plan Wiki Page)

### Estimated Time

10 min

### Deadline

01 Oct 2024

### Reviewer

@danzio19

**Comment by rukiyeaslan** [comment]
This task is completed and corresponding wiki page can be [here](https://github.com/bounswe/bounswe2024group2/wiki/Communication-Plan/6e66be862acc24591d5880406d50006c6e4f7116).
This issue can be reviewed by @danzio19

**Comment by danzio19** [comment]
The updated communication plan successfully reflects what has been decided upon by the group during Lab #2, therefore this issue is closed.
