### ISSUE TITLE
Take lab report notes

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#225]
### Description

Take lab reports about what we did, couldn't upload to github since I don't have access yet.

### Required Activities

- [x] Take lab report notes

### Estimated Time

2

### Deadline

01.10.2024

### Reviewer

@furkansenkal

**Comment by furkansenkal** [comment]
I checked the lab report notes and everything looks fine, good job Cem, I'm closing the issue.
