### ISSUE TITLE
Archive CmpE352 main wiki page

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#227]
### Description

CmpE352 course is ended. So, we do not need old wiki pages. We will archieve old pages. Only new pages related with CmpE452 course will be visible at first sight.

### Required Activities

- [x] Archieve old pages in main wiki page
- [x] Show new pages in main wiki page

### Estimated Time

0.5 hours

### Deadline

02.10.2024

### Reviewer

@furkansenkal

**Comment by mahmutbugramert** [comment]
Archieved old wiki pages and added new pages.  Lab meeting notes are gathered under meeting notes title. However, they can be gathered under Lab meeting notes title later. Changes can be seen from [here](https://github.com/bounswe/bounswe2024group2/wiki). Issue is open to review @furkansenkal

**Comment by furkansenkal** [comment]
It is not appropriate for the CMPE352 archive to appear in the new home. It would be better to archive the old main page and remove it from the new home completely.

**Comment by mahmutbugramert** [comment]
CmpE352 archieve is removed from both wiki home page and wiki side bar. CmpE352 archieves can be reached from following links: [home page](https://github.com/bounswe/bounswe2024group2/wiki/Home%E2%80%90SemanticFlix), [side bar](https://github.com/bounswe/bounswe2024group2/wiki/SideBar%E2%80%90SemanticFlix). Changes can be reviewed now @furkansenkal

**Comment by furkansenkal** [comment]
Great work but we have decided to keep the CmpE352 archive in the sidebar. Could you please add it to the sidebar again.

**Comment by mahmutbugramert** [comment]
Added CmpE352 archieve to do wiki sidebar as a dropdown menu named "SemanticFlix Archieve". You can see it [here](https://github.com/bounswe/bounswe2024group2/wiki). Issue is open to review again @furkansenkal.

**Comment by furkansenkal** [comment]
I have checked your work and it is now very satisfactory. Thank you. I am closing the issue.
