### ISSUE TITLE
Create personal page [mahmutbugramert]

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#228]
### Description

Personal pages from CmpE352 course contains weekly efforts. Therefore, create new personal page for CmpE451 course.

### Required Activities

- [x] Create personal page
- [x] Add it to wiki main page and sidebar

### Estimated Time

0.2

### Deadline

02.10.2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by mahmutbugramert** [comment]
Created my personal wiki page and added to the wiki main page and sidebar. My page can be seen from [here ](https://github.com/bounswe/bounswe2024group2/wiki/Mahmut-Bu%C4%9Fra-Mert-CmpE452). Issue is open to review @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Everything looks good! I am closing this issue
