### ISSUE TITLE
Create personal page [furkansenkal]

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#229]
### Description

Personal pages from CmpE352 contains weekly efforts. Therefore, new personal page for CmpE451 should be created.

### Required Activities

- [x] Create personal page
- [x] Add it to wiki main page and sidebar

### Estimated Time

0.2

### Deadline

02.10.2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
Created my personal wiki page and added it to the wiki main page and sidebar. My page can be found [here ](https://github.com/bounswe/bounswe2024group2/wiki/Furkan-Şenkal-CmpE451).
Issue is ready to be reviewed by @m-erkam

**Comment by m-erkam** [comment]
The page is prepared and accessable. First week efforts can be added to contributions. Well done!
