### ISSUE TITLE
Take Lab Meeting Notes - Week 2

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#230]
### Description

Second lab of the semester will be held on 1st Oct, 2024.

### Required Activities

- [x] (Take notes during lab)
- [x] (Document notes to the wiki)

### Estimated Time

2h

### Deadline

1 Oct 2024

### Reviewer

@cemgungor1

**Comment by furkansenkal** [comment]
Lab notes can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/2nd-Lab-Meeting-Report,01.10.2024).
This issue is completed and ready for a review by @cemgungor1

**Comment by cemgungor1** [comment]
Everything looks fine! I'm closing this issue.
