### ISSUE TITLE
Create Personal Page [Rukiye Aslan]

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#231]
### Description

Add a new personal information and efforts page.

### Required Activities

- [x] Create the page
- [x] Link it to the sidebar 
- [x] Link it to the wiki main page

### Estimated Time

20 min

### Deadline

3 Oct 2024

### Reviewer

@mahmutbugramert

**Comment by rukiyeaslan** [comment]
The corresponding page is created and can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Rukiye-Aslan-%E2%80%90-Cmpe451/d38a96a1294fc3a73693998bdb872836ff4a881d). This issue is ready for a review by @mahmutbugramert 🙌🏼

**Comment by mahmutbugramert** [comment]
Page is created and can be accessed from both wiki main page and side bar. Well Done!
