### ISSUE TITLE
Create Personal Page [Muhammed Erkam Gökcepınar]

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#233]
### Description

Create a new personal page for Cmpe 451. Add personal information and efforts to the page.

### Required Activities

- [x] Create the page
- [x] Link it to the sidebar
- [x] Link it to the wiki main page

### Estimated Time

0.5

### Deadline

4 October 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by m-erkam** [comment]
I have created my personal page. It can be accessed in sidebar and wiki main page. The issue can be closed after being reviewed by @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Everything on the homepage looks great, but I noticed the LinkedIn link isn't working properly. Once that's fixed, could you also comment out the revision link of the page to the issue before closing it? Thanks!

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Just a friendly reminder, make sure to add any tasks you reviewed to your weekly contribution section.

**Comment by m-erkam** [comment]
I revised my Linkedin link, so it should be accessable right now. I will add reviewed tasks by myself afterwards, thanks!

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Closing the issue then. Good Job
