### ISSUE TITLE
Create Personal Page [Kamil Deniz Coşkuner]

### ISSUE THREAD

**Issue by danzio19** [bounswe/bounswe2024group2#234]
### Description

Add a new personal information and efforts page.

### Required Activities
- [x] Create the page
- [x] Link it to the sidebar 
- [x] Link it to the wiki main page

### Estimated Time

20 min

### Deadline

3 Oct 2024

### Reviewer

@rukiyeaslan

**Comment by danzio19** [comment]
All required activities are completed and can be reviewed from [here](https://github.com/bounswe/bounswe2024group2/wiki/Kamil-Deniz-Co%C5%9Fkuner-CMPE451).

**Comment by rukiyeaslan** [comment]
The page is created and looks nice. Well done.
