### ISSUE TITLE
Create the First Draft of the Requirements - Glossary

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#238]
### Description

Out of the created Requirements draft, we need to carefully identify key terms and concepts that are crucial for understanding the project. This involves reviewing the draft thoroughly to highlight terminology that may require clarification or that are specific to our domain. Each identified term should be defined clearly and concisely in the Requirements Glossary section. Integrate the Requirements Glossary as a dedicated section within the existing requirements page

### Required Activities

- [x] Compile Requirements Glossary
- [x] Document wiki page

### Estimated Time

3

### Deadline

08 October 2024

### Reviewer

@m-erkam

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
The first version of the glossary is created and it is accessible via the wiki sidebar. See the requirements glossary section [here](https://github.com/bounswe/bounswe2024group2/wiki/Requirements-%E2%80%90-Cmpe-451/8e4470a92a567f97913c8a299c517d7bfee96cb8#glossary)
Up for rev @m-erkam

**Comment by m-erkam** [comment]
Glossary is well prepared and can be accessable. Nice work!
