### ISSUE TITLE
Research W3C Standards [Rukiye Aslan] 

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#239]
### Description

A research on W3C standards should be conducted to use on for our project. After the research, the most ideal one for our project will be suggested by Rukiye and discussed with the team.

### Required Activities

- [ ] Go through [W3C](https://www.w3.org/) documents.
- [ ] Pick one standard and present it to the team with reasons.

### Estimated Time

2h

### Deadline

8 Oct 2024

### Reviewer

@cemgungor1

**Comment by rukiyeaslan** [comment]
I completed my research and shared what I learned with the team, this issue is up for a review by @cemgungor1.

**Comment by cemgungor1** [comment]
Thank you for your sharings Rukiye, they were valuable. I'm closing this issue
