### ISSUE TITLE
Create a Meeting Notes Template

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#24]
Create a brief template for meeting notes, add it to the templates section of the wiki.

This template will be used to keep things organized when documenting meeting notes on the wiki.

**Comment by iremnuy** [comment]
Initial template can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Meeting-Minutes-Template), I am open to any feedback, suggestion and help.I recently added an "Action Items" header.

**Comment by iremnuy** [comment]
Yes, that would be better, I added the checklist and changed the format to a more general template, also added a decisions section to be able to note the key decisions made during the meeting.
