### ISSUE TITLE
Create the First Draft of the Requirements - Non Functional Requirements

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#240]
### Description

The first draft of the requirements for our project should be written. The requirements consists of 4 parts and this issue concerns `non functional requirements` part.

### Required Activities

- [x] Non-functional requirements should be written.
- [x] The corresponding part should be documented on wiki.

### Estimated Time

2h

### Deadline

8 Oct 2024

### Reviewer

@furkansenkal

**Comment by rukiyeaslan** [comment]
The first draft of non functional requirements can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Requirements-%E2%80%90-Cmpe-451/8e4470a92a567f97913c8a299c517d7bfee96cb8).
This task is completed and ready for a review by @furkansenkal

**Comment by furkansenkal** [comment]
I checked the non-functional requirements, there was a mistake in the enumeration and I fixed it. The requirements look good. Thank you. I'm closing the issue.
