### ISSUE TITLE
Make a research about tools for graphics manipulation in React Native

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#241]
### Description

In order to implement the price visualization part of our stock market mobile application, it is needed to make a research about graphics libraries in React Native

### Required Activities

- [x] Find some tools for graphics manipulation
- [x] List pros and cons of the tools

### Estimated Time

3

### Deadline

8 October 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
I have found lots of libraries for using charts in React Native like Anychart, CLCcharts and react-native-responsive-linechart. These are really powerful packages but many of them is lack of React JS compatibility. 
To use the chart library in both parts of our application - in mobile and in web- the "Anychart " library is suitable and has enough properties that fullfill our needs in drawing financial charts.

**Comment by m-erkam** [comment]
Issue can be reviewed by @furkansenkal.

**Comment by furkansenkal** [comment]
Anychart library seems to be compatible for both web and mobile as you mentioned. We can continue with this. Thanks for your work.
