### ISSUE TITLE
Create the First Draft of the Requirements - System Requirements

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#242]
### Description

Requirements should be written for our stock market project and system requirements will be handled in this issue.

### Required Activities

- [x] System requirements should be written
- [x] These requirements should be documented in the wiki

### Estimated Time

2

### Deadline

8 October 2024

### Reviewer

@cemgungor1

**Comment by m-erkam** [comment]
First draft of the system requirements is prepared and can be accessed [here](https://hackmd.io/wvbzc_JKQnOXzEDaZR1flw). After revising the requirements draft, it should be added to wiki

**Comment by m-erkam** [comment]
Issue can be reviewed by @cemgungor1

**Comment by cemgungor1** [comment]
I reviewed the wiki page and everything looks fine. Well done @m-erkam! I'm closing this issue.
