### ISSUE TITLE
Create the First Draft of the RAM Page

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#245]
### Description

A new RAM page should be created and added to the wiki for our new project.

### Required Activities

- [x] The First Draft of the RAM Page should be created.
- [x] It should be added to the wiki and sidebar.

### Estimated Time

2

### Deadline

08 Oct 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by furkansenkal** [comment]
The First Draft of the RAM Page created on the wiki and added to the sidebar. You can take a look at it form [here](https://github.com/bounswe/bounswe2024group2/wiki/Responsibility-Assignment-Matrix-451/da35d2e49e312445240fceb77a6092ccc700c945).

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Reviewed your RAM page initiation. It looks well-structured and has been successfully added to the wiki and sidebar. No further changes needed. Closing the issue. Great job!
