### ISSUE TITLE
Create the First Draft of the Requirements - User Requirements

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#246]
### Description

The requirements of the new project must be written. Before elicitation questions create an initial draft of user requirements.

### Required Activities

- [x] Write user requirements
- [x] Add it to the wiki page

### Estimated Time

2 hours

### Deadline

08.10.2024

### Reviewer

@danzio19

**Comment by mahmutbugramert** [comment]
Initial user requirements are written in common HackMd note. You can see it [here](https://hackmd.io/wvbzc_JKQnOXzEDaZR1flw). After further improvements, first requirements draft will ne uploaded to the wiki page.

**Comment by danzio19** [comment]
Initial draft looks good, great job! Therefore this issue is closed.
