### ISSUE TITLE
Create Personal Page [Rafet Oğuz Pançuk]

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2024group2#249]
### Description

Create a new personal page for Cmpe 451. Add personal information and efforts to the page.

### Required Activities

- [x] Create the page
- [x] Link it to the sidebar
- [x] Link it to the wiki main page

### Estimated Time

0.5

### Deadline

04.10.2024

### Reviewer

@m-erkam

**Comment by oguzpancuk** [comment]
I have created my personal page. It can be accessed in sidebar and wiki main page. The issue can be closed after being reviewed by @m-erkam

**Comment by m-erkam** [comment]
Personal page and contents are working and can be accessable via sidebar and wiki main page. Nice job!
