### ISSUE TITLE
Research W3C Standards [Cem Güngör]

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#250]
### Description

There is a need for Cem Güngör to conduct research on the listed topics below in order to create web technologies that are fair, publicly accountable, and of high quality. Documentation of W3C standards should be read and one should be selected to implement on our project

### Research Topics

- W3C standards 

### Materials to Consume

- [W3C standards](https://www.w3.org/standards/)

### Acceptance Criteria

- [x] Materials are consumed

### Deadline

09.10.2024

**Comment by cemgungor1** [comment]
On the weekly meeting we decided on annotations for implementing W3C standards on the project.

**Comment by rukiyeaslan** [comment]
The knowledge gained from the research was shared with the team, good job!
