### ISSUE TITLE
Create the First Draft of the User Scenarios

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#251]
### Description

The first draft of the user scenarios should be created and added to the wiki. Each of them must be reflecting various aspects and advantages of our app. We will try to choose illustrative characters from different démagogique groups. For each scenario, there should be five different parts:
- Background info
- Intents of user
- Preconditions
- Actions
- Related requirements

### Required Activities

- [x] First user scenario should be created.
- [x] Second user scenario should be created.
- [x] Third user scenario should be created.
- [x] Fourth user scenario should be created.
- [x] Fifth user scenario should be created.
- [x] Related wiki page should be created and added to the sidebar.

### Estimated Time

5

### Deadline

13 Oct 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
Cem and I created a new wiki page for user scenarios and added the first two scenarios to it. You can check it out [here](https://github.com/bounswe/bounswe2024group2/wiki/User-Scenarios-451/f1c1a40b17368557aa1b6cbb6ef93966f66ddacc).

**Comment by furkansenkal** [comment]
Cem and I added the draft of third user scenario to related wiki page. You can check it out [here](https://github.com/bounswe/bounswe2024group2/wiki/User-Scenarios-451/62232f6d80aaf1d9c16f83c045e279924c3b1b80).

**Comment by furkansenkal** [comment]
I have added the draft of the fourth user scenario to the relevant wiki page. You can check it out [here](https://github.com/bounswe/bounswe2024group2/wiki/User-Scenarios-451/d7a56a099769be1bf86652ba6bf717aa3adb2b17). After Cem completes the last one we will review them together and add the related requirements section for all of them.

**Comment by cemgungor1** [comment]
I have added the last user scenario to the relevant wiki page. You can check it out [here](https://github.com/bounswe/bounswe2024group2/wiki/User-Scenarios-451/1afa50052d4c6ad6a799e9e56580dee7f9363991). We'll be reviewing last two scenarios and add the necessary requirements section to all five scenarios with Furkan.

**Comment by m-erkam** [comment]
All scenarios are prepared and reflecting our possible users as well. Requirements are linked to each of the scenarios properly. Good work!
