### ISSUE TITLE
Make a research about tools for graphics manipulation in React.js

### ISSUE THREAD

**Issue by danzio19** [bounswe/bounswe2024group2#252]
### Description

You need to do this, do thaIn order to implement the price visualization part of our stock market web application, it is needed to make a research about graphics libraries compatible with React.js

### Required Activities

- [x] Find some tools for graphics manipulation
- [x] List pros and cons of the tools

### Estimated Time

3 hours

### Deadline

8 Oct 2024

### Reviewer

@mahmutbugramert

**Comment by danzio19** [comment]
The research was done and the tools were demoed in the Lab3, we can close this issue @mahmutbugramert .

**Comment by danzio19** [comment]
The research was done and the tools were demoed in the Lab3, we can close this issue @mahmutbugramert .

**Comment by mahmutbugramert** [comment]
Thank you for your efforts. I am closing the issue since requirements of the task is met.
