### ISSUE TITLE
Market Data API research

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#254]
### Description

There is a need for Cem Güngör to conduct on research on the APIs about historical market data and their limitations, an example would be yfinance.

### Required Activities

- [x] Find websites and libraries that we can use to fetch historical market data
- [x] Present the limitations, pros and cons to the team

### Estimated Time

3

### Deadline

15.10.2024

### Reviewer

@danzio19

**Comment by cemgungor1** [comment]
Presented to team, issue is done. Ready to be reviewed by @danzio19

**Comment by danzio19** [comment]
All the required activities are completed and reviewed, hence this issue is closed.
