### ISSUE TITLE
Connect Database to API

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2024group2#255]
### Description

Create requisite connection strings for API and test them.

### Required Activities

- [x] Create the connection strings
- [x] Test the connection strings

Subtasks will be provided soon

### Estimated Time

4

### Deadline

15.10.2024

### Reviewer

@cemgungor1

**Comment by oguzpancuk** [comment]
Connection strings are created, tested and configuration to docker files is added. Waiting for review from @rukiyeaslan.

**Comment by rukiyeaslan** [comment]
@cemgungor1 this issue can be reviewed.
