### ISSUE TITLE
[BE] API connection to swagger

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#256]
### Description

Connect API to swagger in order to use it throughout the development process

### Required Activities

- [x] Configure swagger settings
- [x] Connect project to swagger

### Estimated Time

3

### Deadline

15.10.2024

### Reviewer

@oguzpancuk

**Comment by cemgungor1** [comment]
This development is done and is ready to be reviewed by @oguzpancuk

**Comment by oguzpancuk** [comment]
Review done, all seems fine.
