### ISSUE TITLE
[BE] Dockerize backend application

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#257]
### Description

Dockerization part of the backend application should be  completed.

### Required Activities

- [x] Dockerfile should be created
- [x] docker-compose.yml should be configured
- [x] Environment variables should be set
- [x] Django settings should be configured

### Estimated Time

5h

### Deadline

15 Oct 2024

### Reviewer

@cemgungor1

**Comment by rukiyeaslan** [comment]
All sub tasks for this issue are completed, and corresponding pr is merged into `dev` branch. This issue is up for a review by @cemgungor1.

**Comment by cemgungor1** [comment]
I've already checked the pr, all required activities are completed, closing this issue
