### ISSUE TITLE
Create a new Account on Digital Ocean

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#258]
### Description

Since our past account on Digital Ocean spent most of its free credits, we need a new team member to create an account on behalf of the team, so that we can use Digital Ocean during the term.

### Required Activities

- [x] Create a new Digital Ocean Account
- [x] Add free credits to the newly created account
- [x] Publish credentials with team members via Discord

### Estimated Time

2

### Deadline

15 Oct 2024

### Reviewer

@rukiyeaslan

**Comment by m-erkam** [comment]
I have created the new Digital Ocean account linking with my github-education account, then I claimed free 200$ credits. I have added my team member @Halil-Ibrahim-Kasapoglu to the team in Digital Ocean, since the droplets can be created and used. 
Issue can be reviewed by @rukiyeaslan

**Comment by rukiyeaslan** [comment]
Account is created and credentials are shared with the team, well done.
