### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#26]
Create a default issue template and a default configuration file for issue templates of the project.

To create an issue template, follow the steps in the following article: [Configuring issue templates for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Created the 'issue-templates' branch specifically for addressing this issue and linked it. Will be updating the templates on this branch

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
There are different ways to configure templates. One can define .md files or configure them by utilizing YAML. YAML allows us to create more appealing and interactive templates. Thus there is a need to study YAML configurations

- [ ] #36

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Created a new label for issues that are created using a template. The label is 'issue templates'. Will configure the YAML files so that templates will automatically add this label, enabling us to monitor its implementation.
