### ISSUE TITLE
Configure Droplet on Digital Ocean 

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#260]
### Description

We need to have a working droplet machine on Digital Ocean to deploy our App. The droplet should allow us to handle our web and API services. Configuration also requires setting remote access to the droplet so that we can manage our machine.

### Required Activities

- [x] Create a droplet on Digital Ocean
- [x] Configure remote access to the machine
- [x] Share SSH keypairs with the team via Discord

### Estimated Time

4

### Deadline

17 Oct 2024

### Reviewer

@rukiyeaslan

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have created two VM(droplet) on Digital Ocean called master and worker. One will be for our control plane. I have decided to go with password login instead of ssh keypairs as it seems much more practical even though it seems less secure. I have published connection settings to those machines in our private Discord channel. This issue can be reviewed @rukiyeaslan.

**Comment by rukiyeaslan** [comment]
All configurations are completed nicely, good job Halil!
