### ISSUE TITLE
Initialize Mobile Development

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#261]
### Description

The login page should be created and new project files should be pushed to repository

### Required Activities

- [x] Create login page
- [x] Push the mobile project to repository

### Estimated Time

2

### Deadline

15 October 2024

### Reviewer

@rukiyeaslan

**Comment by m-erkam** [comment]
Simple login page and page navigation part is created. #308 can be reviewed and merged by @furkansenkal

**Comment by furkansenkal** [comment]
I reviewed your work, simple login page looks nice and navigation drawer works smoothly. Thank you for your work, I am closing the issue.
