### ISSUE TITLE
Take Lab Reports - Week 3

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#262]
### Description

Lab report for week 3 should be created and documented on wiki.

### Required Activities

- [x] Write lab report.
- [x] Document lab report on wiki.
- [x] Connect lab report link to the sidebar. 
- [x] Connect lab report link to the wiki main page. 

### Estimated Time

2h

### Deadline

8 Oct 2024

### Reviewer

@cemgungor1

**Comment by rukiyeaslan** [comment]
Lab report was documented and linked to the corresponding parts on wiki. Wiki page can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Lab-Report-%233).
This task can be reviewed by @cemgungor1.

**Comment by cemgungor1** [comment]
I checked the lab report notes and everything looks fine, good job Rukiye, I'm closing the issue.
