### ISSUE TITLE
Initialize Mobile Development Environment

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#263]
### Description

We need to choose the necessary tools we will use for mobile development and make them work successfully on our personal devices. 

### Required Activities

- [x] Mobile development environment should be established.
- [x] Mobile development environment should be tested.

### Estimated Time

3

### Deadline

13 Oct 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
I set up my personal mobile development environment and tested it. We have decided to use Expo with React Native. Issue is ready to be reviewed.

**Comment by m-erkam** [comment]
As mobile team we have decided on some issues and personal environments are set up. Issue is closed
