### ISSUE TITLE
Add Lab Meeting Notes 3

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#264]
### Meeting Details

- Meeting 3
- Date: 08.10.2024
- Note Taker: @m-erkam 
- Platform: Discord

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Reviewer

@danzio19

### Deadline

08.10.2024

**Comment by m-erkam** [comment]
Meeting notes are documented in wiki and it can be seen via sidebar. The issue can be reviewed by @danzio19

**Comment by danzio19** [comment]
All the required activities are completed and reviewed, hence this issue is closed.
