### ISSUE TITLE
Initialize Git Environment for Web Development

### ISSUE THREAD

**Issue by danzio19** [bounswe/bounswe2024group2#265]
### Description

The Git environment for the web development of our new project needs to be initialized by creating a branch web and creating and pushing an empty React project to the branch.

### Required Activities

- [x] Create a branch for web
- [x] Create empty React project and push to the branch

### Estimated Time

45 minutes

### Deadline

10 Oct 2024

### Reviewer

@mahmutbugramert

**Comment by danzio19** [comment]
The git environment for frontend development is set. You can review it from [here](https://github.com/bounswe/bounswe2024group2/tree/frontend) @mahmutbugramert.

**Comment by mahmutbugramert** [comment]
It looks perfect. Thank you. I am closing the issue since required activities are met.
