### ISSUE TITLE
Deploy the App on Digital Ocean

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#266]
### Description

Deploy both API and web services on digital ocean. Make sure they are accessible through a public IP address. Make sure it is working API.

### Required Activities

- [x] Deploy the Web application
- [x] Deploy the API on Digital Ocean
- [x] Expose droplet(s) to outer world
- [x] Test web application deployment status
- [x] Test API deployment status

### Estimated Time

6 hours

### Deadline

20 Oct 2024

### Reviewer

@danzio19

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Related to issue #270. 

_It is also possible to check out simple deployed API and Web client over node port_ 
- [API](http://159.223.28.163:30002/docs/)
- [WEB](http://159.223.28.163:30001)

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Up for rev @danzio19

**Comment by danzio19** [comment]
All the required activities are completed successfully, hence this issue is closed.
