### ISSUE TITLE
Initialize Git Environment for Mobile Development

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#267]
### Description

Necessary Git work should be done to start mobile development. Mobile branch should be created and run smoothly.

### Required Activities

- [x] The mobile development part of the project should be added to the related Git branch (dev).
- [x] The Branch's functionality must be tested and run properly.

### Estimated Time

3

### Deadline

13 Oct 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
I added mobile folder with a blank react native project in it to the dev branch and modified gitignore according to this. Blank project tested and works normal. Issue is ready to be reviewed.

**Comment by m-erkam** [comment]
React Native project is successfully initialized and ready for development. Good work!
