### ISSUE TITLE
Configure Github Actions Yaml for Auto Deploy

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#268]
### Description

The last term in Cmpe 352 it was bothersome to manually deploy our application to the Digital Ocean Environment. To handle auto deploys on merges, we decided to utilize GitHub Actions. We need to configure Github Action Yamls, and add secret variables for connections. 

### Required Activities

- [x] Set up secrets and vars for the repository
- [x] Create GitHub Actions Yamls for deployment on the main branch merge
- [x] Test the deployment is working fine

### Estimated Time

8 hours

### Deadline

21 Oct 2024

### Reviewer

@oguzpancuk

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have request assistant to add our secrets to repo

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Created the dev auto deploy yaml and tested. [Here](https://github.com/bounswe/bounswe2024group2/blob/main/.github/workflows/dev-deploy.yml) is the file I have added.
Also [here](https://github.com/bounswe/bounswe2024group2/actions/runs/11426069218) is the first successful auto deploy on dev 🎉 

I will be closing this issue once you reviewed @oguzpancuk

**Comment by oguzpancuk** [comment]
Review done, all seems fine.
