### ISSUE TITLE
Implement Simple Login Page in Web Frontend

### ISSUE THREAD

**Issue by danzio19** [bounswe/bounswe2024group2#269]
### Description

We need implement a simple version of our web app's login page. It will only have some input fields, and no actual login authorization logic.

### Required Activities

- [x] Implement simple login page

### Estimated Time

30 minutes

### Deadline

14 Oct 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by mahmutbugramert** [comment]
I created a mock login page. Here is the [branch](https://github.com/bounswe/bounswe2024group2/tree/feature/FE-login-draft).

**Comment by mahmutbugramert** [comment]
Issue now is open to review @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Can you create a pull request as It will be easier for me to review what has changed.

**Comment by mahmutbugramert** [comment]
A pull request is created and linked with this issue. You may see the changes clearly now.
