### ISSUE TITLE
Configure K8s Environment 

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#270]
### Description

Create a minikube cluster since it will be sufficient for our needs. Manage our services over k8s as it will benefit us if our application is down etc. Also, it will be better for our team to debug application on remote.

### Required Activities

- [x] Create K8s deployment and service yamls
- [x] Set up K8s in a remote machine of Digital Ocean
- [x] Create deployments of our application
- [x] Expose our app to outer world 
- [x] Expose k8s dashboard
- [x] Test app is working and accessible 

### Estimated Time

2 days

### Deadline

22 Oct 2024

### Reviewer

@m-erkam

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have set up a simple master & worker nodes on our csp. I have exposed the k8s dashboard and provided token and URL for that in our private discord server. Will be working on creating deployment yamls of our application.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have manually k8s yamls. And deployed our application pods there. They are now accessible. Here I give an ss of the current status of the dashboard.
<img width="1505" alt="Screenshot 2024-10-19 at 14 11 53" src="https://github.com/user-attachments/assets/f6341dbe-9757-4948-ade1-ceaf6740b85e">

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
It is also possible to check out simple deployed API and Web client over node port 
- [API](http://159.223.28.163:30002/docs/)
- [WEB](http://159.223.28.163:30001)

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
This task is up for rev @m-erkam .

**Comment by m-erkam** [comment]
Deployed API and Web client is examined and they are working well with k8s. Good work!
