### ISSUE TITLE
Create Quickstart Documentation

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#272]
### Description

Create a 451 Quickstart documentation, describe the dependencies, and clearly create a how-to guide on configuring the application. 

### Required Activities

- [x] Create a quickstart documentation
- [x] Link it to the wiki page  

### Estimated Time

6 hours

### Deadline

22 Oct 2024

### Reviewer

@furkansenkal

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Quickstart is available both in readme and wiki footer. 
[Here](https://github.com/bounswe/bounswe2024group2/wiki/Quickstart-451/8a8fd5b8c68cca86ff8e89452271d2f441ca1b07) is a direct link to my last edition. 
Will be closing this after rev @furkansenkal

**Comment by furkansenkal** [comment]
I reviewed your work and it looks fine. Thank you, closing the issue.
