### ISSUE TITLE
Create First Draft of the Requirements

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#273]
### Description

The initial draft of the requirements should be uploaded to the wiki.

### Required Activities

- [x] Requirements wiki page should be created 
- [x] The first draft should be uploaded to that page

### Estimated Time

0.5

### Deadline

8 October 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Wiki page is created and requirements are uploaded. The page can be accessable through sidebar. The issue can be reviewed by @furkansenkal

**Comment by furkansenkal** [comment]
I checked the wiki page, there was a small problem with the numbering, I fixed it for you. Other than that it looks pretty good. Thanks for your work. Closing the issue.
