### ISSUE TITLE
Create Sequence Diagrams

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#274]
### Description

Sequence diagrams for the project should be created and uploaded to the wiki page. Last term, we used [Planttext](https://www.planttext.com/) for Sequence diagrams. It can be used for this project aswell.

### Required Activities

- [x] Create Sequence diagrams for user types
  - [x] Create Sequence diagrams for Registered user
  - [x] Create Sequence diagrams for Guest user
  - [x] Create Sequence diagrams for Admin
- [x] Upload Sequence diagrams to the wiki page

### Estimated Time

3 hours

### Deadline

17.10.2024

### Reviewer

@m-erkam

**Comment by mahmutbugramert** [comment]
Met with Rukiye in lab and discussed how to create sequence diagrams. I created sequence diagrams for admin and half of registered user. You can see it [here](https://github.com/bounswe/bounswe2024group2/wiki/Sequence-Diagrams-CmpE451).

**Comment by rukiyeaslan** [comment]
This issue is up for a review by @m-erkam.

**Comment by m-erkam** [comment]
For all user types, sequence diagrams are well designed and created. Good job!
