### ISSUE TITLE
Create Use Case Diagrams

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#279]
### Description

Use case diagrams for the project need to be created and uploaded to the wiki page. In CmpE352, we used PlantUML for the use case diagrams. It can be helpful for this project as well..

### Required Activities

- [x] Create use case diagrams
- [x] Create a wiki page for use case diagrams

### Estimated Time

3 days

### Deadline

22 Oct 2024

### Reviewer

@danzio19

**Comment by furkansenkal** [comment]
I created a draft use case diagram by using PlantUML. You can have a look [here](https://www.plantuml.com/plantuml/png/RPLFZp8f4CRlV8hAUz9DtfYzxc4p-CU-p2ZHj7Usksp981YWnpLcllisD3r0tCj8FSypFweBfT-iuyRrLqaadXqu3KPq5mUjCDWueHMndqBTkE5NkF7catTuT0-9uEtCuutJ1fu4060vv3gZUzMkj1nKnYKkPO-ZgKsBPZI2-4r814DjqTWd8IFiW9sm3WssNWTkeOvErQDrNgY8__THfErLA2zIGXAIQUjiw6ksqjShAWTxDQfp7rxjcVTg9SKdPdeTv9L1xYOvv2n2PVZj4bEL5xTQIdqFtGTrMuENtqlYEoE3MiFltt-_WgFyph9YMsT5dJj3qtCFe_yFepcCvZ2QmsW9Ap63zySGhERm5mZLoBxrn-V77ISxpbjOPxWJN_XCm2LNuonyEZi8uyvQ2lqivANHTukBay3xaypyHsmWBy9VRE6V1uop5geBCpqnjXs3qK1ZHoFAeH5WHf-5n6ZLevKwYZgB-WxlKTb5PVDlS-6gGpXmDr4s1p8x8ZVD9UmngiTw4hE3Fp92I3ov_06Zv9yX5TbobqNIiaxBpU5dVQpJqXzdzRfTbR1LmbO9MsNOAc6h34jViJGzHIgovIwBf6NjbsaxchQRbgpy-cnQuHRrhUKE5skKw12UXCoy3FkxmdOwv33opHuWcbGzIejEWzhiVtRRq7d9qjP544kSJAOiKLY6OGCdjbUIOEr9qIfOwyHQPwn1BdfANzUfiKFUMMdImKpzfG5x8-_mbRlstABFqix8FfgrwulYo6ZlBgYSQBX_ZuGhc3ODtXmm8xvuuzbID8y0fepvm0cDE3_WWmiPvDC7PBUZxeIQ5xNkdHTe7aXr2bIZCBrIl3HRXT_qOgjDfnqmRkrTctPyAx04MSMRDokgl4XG-FNdBtzlXiyPPQoyF7s-Z9m-yiGtUKFLzbVv7m00). We can improve it and make it complete.

**Comment by cemgungor1** [comment]
We have to revise use case diagrams so that they fit better with the user needs and relate to the new requirements. I'm reissuing create use case diagrams activity

**Comment by cemgungor1** [comment]
We worked with Furkan to update the use cases, used generalization to simplify the diagram and decrease associations. All required activities are done, and this issue is ready to be reviewed by @danzio19
