### ISSUE TITLE
Add Backend Meeting #1 Notes

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2024group2#281]
### Meeting Details

- Backend Meeting 1
- Date: 13.10.2024-14.10.2024
- Note Taker: Rafet Oğuz Pançuk
- Platform: Google Meet

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Required Activities

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Estimated Time

0.5

### Deadline

15.10.2024

### Reviewer

@rukiyeaslan

**Comment by rukiyeaslan** [comment]
Notes are documented nicely, good job!
