### ISSUE TITLE
Take Lab Reports - Week 4

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#282]
### Description

Lab report for week 3 should be created and documented on wiki.

### Required Activities

- [x]  Write lab report.
- [x] Document lab report on wiki.
- [x] Connect lab report link to the sidebar.
- [x] Connect lab report link to the wiki main page.

### Estimated Time

2

### Deadline

15 Oct 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by furkansenkal** [comment]
Lab report was documented and linked to the corresponding parts on wiki. Wiki page can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Lab-Report-%234/5a06e4a4a3069707ba84e8951e4170d8f2735562). Issue is ready to be reviewed by @Halil-Ibrahim-Kasapoglu.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Excellent work! I have reviewed your report and respective wiki page. Remember to add it to the sidebar. Then you can close the issue.
