### ISSUE TITLE
Create Onboarding Web Mockups

### ISSUE THREAD

**Issue by danzio19** [bounswe/bounswe2024group2#283]
### Description

Design and draw the web mockups for login, register and forgot password pages according to the requirements and user scenarios

### Required Activities

- [x] Create login page
- [x] Create register page
- [x] Create forgot password page

### Estimated Time

2 hours

### Deadline

18.10.2024

### Reviewer

@mahmutbugramert

**Comment by mahmutbugramert** [comment]
Mockups are uploaded to wiki page. Can be seen [here](https://github.com/bounswe/bounswe2024group2/wiki/Mockups-451). Hereby, I am closing the issue.
