### ISSUE TITLE
Document Weekly Efforts [Mahmut Buğra Mert]

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#284]
### Description

Created my personal page. However, weekly efforts part is missing. Add weekly report title to the wiki page and fill the efforts until this time.

### Required Activities

- [x] Create Weekly Efforts part in personal page
- [x] Fill the efforts until last week.

### Estimated Time

40 mins

### Deadline

25.10.2024

### Reviewer

@oguzpancuk

**Comment by mahmutbugramert** [comment]
Created Weekly Contributions section in my personal page. [Here](https://github.com/bounswe/bounswe2024group2/wiki/Mahmut-Bu%C4%9Fra-Mert-CmpE451/e4e3121b1ce79e8d8350f48fc0dcb56ad034b087)

**Comment by oguzpancuk** [comment]
Review done, all seems fine.

**Comment by oguzpancuk** [comment]
Accidentally closed the issue, reopened it now.

**Comment by mahmutbugramert** [comment]
Important weekly efforts are added. [Here](https://github.com/bounswe/bounswe2024group2/wiki/Mahmut-Bu%C4%9Fra-Mert-CmpE451) you can see. Issue is open to review @oguzpancuk .

**Comment by oguzpancuk** [comment]
Review done, all seems fine. Good documentation!
