### ISSUE TITLE
Add General Meeting #3 Notes 

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#285]
### Meeting Details

- General Meeting 2
- Date: 10.10.2024
- Note Taker: @cemgungor1 
- Platform: Jitsi

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Reviewer

@oguzpancuk

### Deadline

21.10.2024

**Comment by cemgungor1** [comment]
I've added action items and their details to meeting notes page, remaining action items will be added after the issues are opened

**Comment by cemgungor1** [comment]
This issue is now done, all action items are created and up-to-date in general meeting 3 wiki page. Ready to be reviewed by @oguzpancuk

**Comment by oguzpancuk** [comment]
Review done, all seems fine.
