### ISSUE TITLE
Dockerize web application

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#287]
### Description

The dockerization part of the web application should be completed.

### Required Activities

- [x] Dockerfile should be created

### Estimated Time

1 h

### Deadline

18 Oct 2024

### Reviewer

@rukiyeaslan

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Created the dockerfile and made a PR. Up for rev @rukiyeaslan .

**Comment by rukiyeaslan** [comment]
The dockerization for web application is completed nicely, well done.
