### ISSUE TITLE
Create News Page Skeleton for Web

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#290]
### Description

Create the basic structure of the news page without the final styling. Make sure to provide card elements for news. With the scope of the issue, no need to implement real news only mock data. The news page should also allow users to go over subsections and category filter

### Required Activities

- [x] Create the layout for the news page.
- [x] Add placeholders for news articles.
- [x] Include navigation elements to return to the dashboard or other sections.

### Estimated Time

5 hours

### Deadline

19 Oct 2024

### Reviewer

@mahmutbugramert

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have created a pr on this issue. up for rev @mahmutbugramert

**Comment by mahmutbugramert** [comment]
It looks great. Since the codes already merged, I am closing the issue. Great job!
