### ISSUE TITLE
Create a Public Registry 

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#292]
### Description

To automate the process of deployments, we need a registry to publish our images under. I presume docker hub will be enough for our needs. We need to open a registry there and publish our images there.

### Required Activities

- [x] Create Docker Hub Public Registry Account
- [x] Test publishing images over there

### Estimated Time

2 h

### Deadline

19 Oct 2024

### Reviewer

@oguzpancuk

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have created our docker hub registry and our backend(api) and frontend reside there currently. You can pull and test it yourself 🎉 
[Group2 DockerHub](https://hub.docker.com/search?q=24cmpe451group2)

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Up for rev @oguzpancuk

**Comment by oguzpancuk** [comment]
Review done, everything seems fine. Good work. Closing the issue now.
