### ISSUE TITLE
Update User Scenarios [Cem Güngör]

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#294]
### Description

Update user scenarios and related requirements according to the new user requirements

### Required Activities

- [x] Update Scenarios
- [x] Update related requirements section

### Estimated Time

1

### Deadline

22.10.2024

### Reviewer

@furkansenkal

**Comment by cemgungor1** [comment]
I've update all user scenarios according to our new requirements. @furkansenkal you can check the wiki page

**Comment by furkansenkal** [comment]
I have reviewed the user scenarios wiki page. The necessary places have been changed and the related requierements section has become consistent with the final version of the requirements. Thanks cem, I am closing the issue.
