### ISSUE TITLE
[BE] Implement the Registration Endpoint

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#295]
### Description

Registration endpoint should be implemented in backend with the following features:

- A user should enter their unique username
- A user should enter their unique email
- A user should enter their password

to register.

### Required Activities

- [x] Implement the endpoint
- [x] Endpoint should be listed on swagger

### Estimated Time

1h

### Deadline

20 Oct 2024

### Reviewer

@oguzpancuk

**Comment by rukiyeaslan** [comment]
This task is completed and up for a review by @oguzpancuk

**Comment by oguzpancuk** [comment]
Review done, tests are done, registration works.
