### ISSUE TITLE
[BE] Implement Logout endpoint

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#298]
### Description

Logout endpoint should be implemented so that logged in users can logout safely.

### Required Activities

- [x] Logout endpoint should be initialized
- [x] Endpoint should be documented in swagger
- [x] Tokens should be safely destroyed

### Estimated Time

2

### Deadline

22.10.2024

### Reviewer

@rukiyeaslan

**Comment by cemgungor1** [comment]
This issue is done, logout endpoint works fine. Ready to be reviewed by @rukiyeaslan

**Comment by rukiyeaslan** [comment]
@cemgungor1 I checked your work both as a code and on swagger and you did a great job but could you link the PR to this issue, too.

**Comment by cemgungor1** [comment]
@rukiyeaslan Thank you for your feedback, I've linked the pr

**Comment by rukiyeaslan** [comment]
Well done Cem!
