### ISSUE TITLE
[BE] Document backend meeting notes #2

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#299]
### Description

Backend meeting notes should be documented and added to wiki

### Required Activities

- [x] Document meeting notes
- [x] Create wiki page
- [x] Update sidebar

### Estimated Time

1

### Deadline

25.10.2024

### Reviewer

@rukiyeaslan

**Comment by cemgungor1** [comment]
Prioritized other issues, tasks so deadline is updated

**Comment by cemgungor1** [comment]
This issue is now done, wiki page is updated. Ready to be reviewed by @rukiyeaslan

**Comment by rukiyeaslan** [comment]
All tasks are completed nicely, good job Cem!
