### ISSUE TITLE
Research the project part and create a project to track the issues 

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#30]
Learn about the project section of the github and make a research about it to use it efficiently in our repository.

**Comment by rukiyeaslan** [comment]
- Read the documents from github and watched the following tutorial on Youtube: [Github Project Management](https://www.youtube.com/watch?v=oPQgFxHcjAw&ab_channel=goobar)

- Created the first draft of the board and enabled the issues to be automatically added to the board.
- After discussing the details such as names of the tables, issue tags to connect, etc. with the team, the board will be updated.

**Comment by m-erkam** [comment]
- Read the documentation about projects from github and watched the video shared by Rukiye
- Analyzed projects of different github repositories like Godot and React-Native to learn how developers take advantage of the projects
- Took some notes about what kinds of tables and tags can be added

**Comment by mahmutbugramert** [comment]
* Inspected projects of previous groups.
* Made the final checks.

**Comment by mahmutbugramert** [comment]
Researches are done, and a project to track issues is created.
