### ISSUE TITLE
Add General Meeting #4 Notes

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#304]
### Meeting Details

- Meeting 4
- Date: 19.10.2024
- Note Taker: @m-erkam
- Platform: Jitsi

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Reviewer

@oguzpancuk

### Deadline

20.10.2024

**Comment by m-erkam** [comment]
Notes are documented and attached to sidebar and wiki main page, issue can be reviewed by @oguzpancuk

**Comment by oguzpancuk** [comment]
Review done, all seems fine.
