### ISSUE TITLE
[MB] Create Home Page of the Application

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#305]
### Description

We need to create home page which provides basic functionalities like showing the stock prices. For now, this can be achieved with mock data.

### Required Activities

- [x] Initialize home page

### Estimated Time

3

### Deadline

22 October 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Home page is created and  related pull request is #328. After the revision and merge issue can be closed

**Comment by furkansenkal** [comment]
You have created a very good starting point for our home page, well done. I'm closing the issue.
