### ISSUE TITLE
[FE] Create Login-Register-Forgot Password Page Layouts for Web

### ISSUE THREAD

**Issue by danzio19** [bounswe/bounswe2024group2#314]
### Description

Create the basic layout of login, register and forgot password pages, including styling based on the web mockups. Exclude login functionality.

### Required Activities

- [x] Create layout of the login page
- [x] Create layout of the register page
- [x] Create layout of the forgot password page

### Estimated Time

3 hours

### Deadline

21 Oct 2024

### Reviewer

@mahmutbugramert

**Comment by mahmutbugramert** [comment]
Since all tasks are done and codes are merged, I am closing the issue. Well done!
