### ISSUE TITLE
[FE] Create Markets Page for Web

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#316]
### Description

Create a skeleton for the Markets page. Fill the page with mock data. Create page for stocks which can accessed from Markets page.

### Required Activities

- [ ] Create the skeleton of the Markets page
- [ ] Fill the page with mock data
- [ ] Create page for stocks

### Estimated Time

6 hours

### Deadline

22.10.2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Since this issue is merged and completed I will be closing this one. Good job.
