### ISSUE TITLE
[FE] Implement Login-Register-Token Refresh functionalities

### ISSUE THREAD

**Issue by danzio19** [bounswe/bounswe2024group2#322]
### Description

Implement the login and register functionalities by sending requests to the server. Store and manage access and refresh tokens

### Required Activities

- [x] Implement login functionality
- [x] Implement register functionality
- [x] Manage tokens

### Estimated Time

2 hours

### Deadline

21 Oct 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by danzio19** [comment]
Implemented register, login and token refreshing functionalities. It is ready for review in the pr above @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have reviewed and approved your pr! Closing the issue.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Getting this error on deployment server
```
Module not found: Error: Can't resolve 'axios' in '/app/src/components/login'
ERROR in ./src/components/login/Login.js 8:0-26
```
Can you take a look at it @danzio19

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
closed with pr
