### ISSUE TITLE
[MB] Create Profile Page

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#325]
### Description

In order to present our app's distinct functionalities like badges and portfolios, profile page is essential and should be implemented.

### Required Activities

- [x] Create profile page

### Estimated Time

2

### Deadline

22 October 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Profile page is created and the related pr can be accessed #329. Issue can be reviewed by @furkansenkal

**Comment by furkansenkal** [comment]
You have done a quality job, the page looks good. Thank you for your work, this issue can be closed.
