### ISSUE TITLE
Add frontend to docker-file for local test

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#332]
### Description

To run the application on your local machine, we need to dockerize frontend with db and backend.

### Required Activities

- [x] Create a new docker-compose.yaml for whole project
- [x] Add frontend container

### Estimated Time

1h

### Deadline

21 Oct 2024

### Reviewer

@cemgungor

**Comment by rukiyeaslan** [comment]
This issue is resloved with the PR #333 and up for a review by @cemgungor1.

**Comment by cemgungor1** [comment]
I've checked the pr and code looks fine. Closing this issue
