### ISSUE TITLE
Release the latest versıon of the app as a pre-release

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#345]
### Description

We need to create a pre-release versıon of our app including:

- source code
- apk
- details of impementation

### Required Activities

- [x] Add source code
- [x] Add apk
- [x] Add details

### Estimated Time

1h

### Deadline

22 Oct 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by rukiyeaslan** [comment]
Release can be found [here](https://github.com/bounswe/bounswe2024group2/releases/tag/customer-milestone-1)  and ready for a review by @Halil-Ibrahim-Kasapoglu.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Splendid job! So happy to be here closing milestone 1 with success.
