### ISSUE TITLE
Update Class Diagram

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#347]
### Description

The necessary parts of the class diagram should be updated according to the corrections of team members

### Required Activities

- [x] Class diagram is updated

### Estimated Time

1

### Deadline

25 October 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by m-erkam** [comment]
Some connections with users in class diagram are updated. Issue can be reviewed by @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Lgtm
