### ISSUE TITLE
Update Sequence Diagrams

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#348]
### Description

Sequence diagrams need to be updated after changes in requirements.

### Required Activities

- [x] Update sequence diagrams
- [x] Commit changes to wiki

### Estimated Time

1h

### Deadline

24 Oct 2024

### Reviewer

@mahmutbugramert

**Comment by rukiyeaslan** [comment]
I have updated the sequence diagram for post creation and corresponding changes can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Sequence-Diagrams-CmpE451/626767eb7ca088a0369b4db0c96c2a0ae809d228). This issue is ready for a review by @mahmutbugramert.

**Comment by mahmutbugramert** [comment]
New sequence diagrams are added successfully. Well done!
