### ISSUE TITLE
Create Quickstart for Mobile Application

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#350]
### Description

It should be clearly explained how to configure, build and run the mobile application in the quickstart documentation.

### Required Activities

- [x] Add quickstart documentation for mobile app to the existing wiki page

### Estimated Time

1

### Deadline

25 October 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by m-erkam** [comment]
Commands and instructions for setting up the mobile environment and execution are written and uploaded to the quickstart wiki page, it can be accessed [here](https://github.com/bounswe/bounswe2024group2/wiki/Quickstart-451).

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Looks good
