### ISSUE TITLE
[MB] Create Login Page

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#351]
### Description

A stylish and useful login page should be implemented for our members to log in to our App.

### Required Activities

- [ ] Login page created.
- [ ] The page is connected to backend.

### Estimated Time

3

### Deadline

25 Oct 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
I implemented the login page and connected it to backend, issue is ready for @m-erkam 's review.

**Comment by m-erkam** [comment]
Login page is nicely designed and properly connected to backend. Great!
