### ISSUE TITLE
[MB] Create Register Page

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#352]
### Description

A register page should be implemented in the app for new members to register easily and this page should be connected to the backend.

### Required Activities

- [ ] Register page created.
- [ ] The page is connected to backend.

### Estimated Time

2

### Deadline

25 Oct 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
I implemented the register page and connected it to backend, issue is ready for @m-erkam 's review.

**Comment by m-erkam** [comment]
Like the login page, register page is implemented well and backend connection is working. Good job!
