### ISSUE TITLE
[MB] Create Forgot Password Page

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#353]
### Description

A forgot password page should be created so that users who have forgotten their password can renew their password.

### Required Activities

- [x] Forgot password page is created.
- [ ] The page is connected to backend. 

### Estimated Time

2

### Deadline

29 Oct 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
Forgot password page implemented but not yet connected to the backend.

**Comment by rukiyeaslan** [comment]
I believe that we can close this issue as mobile team completed their part. Once backend team implements the endpoint, a new issue for API connection can be opened @furkansenkal.
