### ISSUE TITLE
[MB] Fix Errors, Warns and Alignments

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#354]
### Description

In order for the application to work healthier and look good, an error related to flatlists and a warn from the navigator should be fixed, and the alignment of the header should be made better.

### Required Activities

- [x] Flatlist error fixed.
- [x] Navigation stack warn fixed.
- [x] Header alignment fixed.

### Estimated Time

3

### Deadline

25 Oct 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
All the stated fixes are done and the issue is ready to be reviewed by @m-erkam.

**Comment by m-erkam** [comment]
Fixes correct the header alignment, flatlist error and stack warn. As a recommendation, one pull request may be enough for all these commits. Nice!
