### ISSUE TITLE
Write Milestone 1 Report

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#355]
### Description

Milestone 1 Report should be written.

### Required Activities

The following sections should be written:
   * 1. **Introduction**
   * 2. **Project Status**
   * 3. **Customer Feedback & Reflections**
   * 4. **Deliverables**
   * 5. **Evaluations**
     
      * 5.1 Evaluation of Tools
      * 5.2 Evaluation of Processes
      * 5.3 Evaluation of Status of Deliverables

   * 6. **Requirements Addressed**
               
   * 7. **Individual Contributions**

### Estimated Time

3h

### Deadline

25 Oct 2024

### Reviewer

@m-erkam

**Comment by rukiyeaslan** [comment]
Milestone report is written and can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Milestone-1-Report-%E2%80%90-CMPE451/e11f7a37231761b67cfcc0ef549862119ae13f58).
This issue is up for a review by @m-erkam

**Comment by m-erkam** [comment]
Report is well designed and documented, so it indicates the exact reflections of the customer and evaluations of our team. There are some broken links in deliverables list. When they are fixed, I will close the issue. Well done!
