### ISSUE TITLE
Update Responsibility Assignment Matrix

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#356]
### Description

The RAM page should be updated to include tasks done up to Milestone 1.

### Required Activities

- [ ] The RAM page is updated.

### Estimated Time

3

### Deadline

25 Oct 2024

### Reviewer

@rukiyeaslan

**Comment by furkansenkal** [comment]
I updated the RAM page and after the some corrections done by my teammates, now it includes responsibilities distributed to members up to Milestone 1. You can access the current version [here](https://github.com/bounswe/bounswe2024group2/wiki/Responsibility-Assignment-Matrix-451/e4cfba6819b939710523c8cc9f6a2c6761acb4c6). Issue is open to review from @rukiyeaslan.

**Comment by rukiyeaslan** [comment]
Checked the page, nice work Furkan!
