### ISSUE TITLE
Update User Scenarios With Mockups

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#357]
### Description

User Scenarios should be updated with updated mockups

### Required Activities

- [x] Update each scenario with mockups

### Estimated Time

1

### Deadline

26.10.2024

### Reviewer

@halil-ibrahim-kasapoglu

**Comment by cemgungor1** [comment]
Updates are done, ready to be reviewed by @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Splendid Job! 
All looking good, closing the issue
