### ISSUE TITLE
Create Missing Mobile Mock Ups

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2024group2#359]
### Description

Design and draw the mobile mockups for home, news, profile, community and post mobile pages according to the requirements and user scenarios

### Required Activities

- [x] Create mobile home mock ups
- [x] Create mobile community page mock up
- [x] Create mobile news page mock up
- [x] Create mobile profile page mock up
- [x] Create mobile community post page mock up
- [x] Add mobile mock ups to wiki page

### Estimated Time

4 hours

### Deadline

25.10.2024

### Reviewer

@danzio19

**Comment by oguzpancuk** [comment]
All mock ups added to the wiki page. Waiting for review from @danzio19

**Comment by danzio19** [comment]
All missing mockups are visible in the wiki page. Hence this issue is closed, Well done!
