### ISSUE TITLE
Create Missing Market - Portfolio Mobile Mockups

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#360]
### Description

Missing mobile mockups: markets and portfolio should be created and added to wiki page

### Required Activities

- [x] Markets mockup
- [x] Portfolio mockup
- [x] Add mockups to wiki 

### Estimated Time

3

### Deadline

26.10.2024

### Reviewer

@halil-ibrahim-kasapoglu

**Comment by cemgungor1** [comment]
All mockups are created and wiki page is updated. You can check from [here](https://github.com/bounswe/bounswe2024group2/wiki/Mockups-451). Ready to be reviewed by @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Lgtm! Well done
