### ISSUE TITLE
Document weekly effort [Oğuz Pançuk]

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2024group2#361]
### Description

Created my personal page. However, weekly efforts part is missing. Add weekly report title to the wiki page and fill the efforts until this time.

### Required Activities

- [x] Create Weekly Efforts part in personal page
- [x] Fill the efforts until last week.

### Estimated Time

40 mins

### Deadline

25.10.2024

### Reviewer

@m-erkam

**Comment by oguzpancuk** [comment]
Filled the efforts until last week. Waiting for a review from @m-erkam

**Comment by m-erkam** [comment]
Efforts are nicely documented. Nice!
