### ISSUE TITLE
Add remaining web mockups to wiki

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#362]
### Description

Remaining web mockups for the app should be added to the wiki page. 

### Required Activities

- [x] Add markets page mockup
- [x] Add register page mockup 
- [x] Add login page mockup 
- [x] Add portfolio page mockup 
- [x] Add news page mockup 
- [x] Add community page mockup 

### Estimated Time

3

### Deadline

25.10.2024

### Reviewer

@rukiyeaslan

**Comment by cemgungor1** [comment]
All remaining mockups are added to wiki. Issue is now ready to be reviewed by @rukiyeaslan

**Comment by rukiyeaslan** [comment]
All mockups look great, well done!
