### ISSUE TITLE
[BE] Implement Post Endpoints

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#364]
### Description

Endpoints for post should be implemented so that mobile and frontend teams can connect to backend and db.

### Required Activities

List of endpoints:

- [x] GET
- [x] POST
- [x] DELETE
- [x] UPDATE
- [x] GET all posts

### Estimated Time

2h

### Deadline

7 Oct 2024

### Reviewer

@cemgungor1

**Comment by cemgungor1** [comment]
Great work Rukiye
