### ISSUE TITLE
[BE] Implement Portfolio, Currency and Draft of Stock Tables

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#365]
### Description

In the backend side, endpoints and tables for portfolio, currency, and a draft version of stock should be implemented so that posts can contain related portfolios and stocks in the post table of database.

### Required Activities

The following endpoints should be implemented 

**- for Portfolio:**
- [x]  GET
- [x]  POST
- [x]  DELETE
- [x]  UPDATE
- [x]  GET all portfolios

- for Currency:
- [x] implement model
- [x] Add TRY and USD data as this table will not be modified further

**- for Stock**

- [x] Create the database table
- [x] Implement the draft CRUD endpoints

Note: dynamically fetching the price data for stocks will be implemented later.

### Estimated Time

3h

### Deadline

7 Nov 2024

### Reviewer

@cemgungor1

**Comment by cemgungor1** [comment]
Perfectly implemented, closing this issue
