### ISSUE TITLE
Document git research page

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#37]
We need to create comprehensive documentation for our Git research page. This documentation will serve as a valuable resource for team members. There should be a wiki page and it should be visible on the sidebar under the research section.

**Comment by danzio19** [comment]
Initialized the page with the sections introduction, installation and configuration, and added the page to the sidebar. The sections about git commands and other related information will be added shortly.

**Comment by danzio19** [comment]
Following parts are added: git workflow, branches, and remote repositories. The information is viewed as adequate, therefore the issue is closed.
