### ISSUE TITLE
Discuss the Use of Selected W3C Standard in the Mobile App

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#373]
### Description

As the mobile team, we will work on and decide how W3C Web Annotation Data Model will be enforced in our mobile app.

### Required Activities

- [x] Discuss the usage of Web Annotation Data Model in mobile
- [x] Document the decisions as a report in wiki page and standard PR.

### Estimated Time

2

### Deadline

5 November 2024

### Reviewer

@cemgungor

**Comment by furkansenkal** [comment]
Added the commit resolving this issue [here] (https://github.com/bounswe/bounswe2024group2/commit/a54ccdd84d219f7e5d1b8b463f46c2577d86031e). Issue can be reviewed.

**Comment by cemgungor1** [comment]
Somehow, I missed this, I apologize. Commit looks great
