### ISSUE TITLE
Discuss the Use of Annotation W3C Standard in the Web

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#374]
### Description

As the frontend team, we will work on and decide how W3C Web Annotation Data Model will be enforced in our web application.

### Estimated Time

2 hours

### Deadline

05.11.2024

### Reviewer

@m-erkam

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Added the commit resolving this issue [here](https://github.com/bounswe/bounswe2024group2/pull/372/commits/348afd51b700361ec8777a859dd358ccb5c2fe52).
Up for rev

**Comment by m-erkam** [comment]
Use of annotation in frontend is documented descriptively in the commit. Good job!
