### ISSUE TITLE
Take Lab Reports - Week 7

### ISSUE THREAD

**Issue by danzio19** [bounswe/bounswe2024group2#375]
### Description

Lab report for week 7 should be created and documented on wiki.

### Required Activities

- [x]  Write lab report.
- [x] Document lab report on wiki.
- [x] Connect lab report link to the sidebar.
- [x] Connect lab report link to the wiki main page.

### Estimated Time

2 hours

### Deadline

05 Nov 2024

### Reviewer

@mahmutbugramert

**Comment by danzio19** [comment]
Lab report was documented and linked to the corresponding parts on wiki. Wiki page can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Lab-Report-%235). Issue is ready to be reviewed by @mahmutbugramert .

**Comment by mahmutbugramert** [comment]
Lab report can be seen from wiki sidebar. Thank you!
