### ISSUE TITLE
Document Lab Meeting Notes #4

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#377]
### Meeting Details

- Lab Meeting 5
- Date: 05.11.2024
- Note Taker: @mahmutbugramert 
- Platform: Classroom

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Reviewer

@Halil-Ibrahim-Kasapoglu

### Deadline

06.11.2024

**Comment by mahmutbugramert** [comment]
Notes are documented on wiki page and can be accessed from wiki sidebar. Here is a [link](https://github.com/bounswe/bounswe2024group2/wiki/5th-Lab-Meeting-Report,-06.11.2024). Issue is now up to reivew @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
The link you provided in the recent comment seems broken. Can you fix that

**Comment by mahmutbugramert** [comment]
Thank you for your feedback. I made a change in the title of the page. That's why link did not work. I fixed the link and it works now. Hereby, I am closing the issue.
