### ISSUE TITLE
[BE] Write Unit Tests for Onboarding Endpoints

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#378]
### Description

Unit tests for the endpoints we implemented should be written. Onboarding endpoints such as login, register, verify email, and logout fall into this category.

### Required Activities

- [ ] Login endpoint tests
- [ ] Register endpoint tests
- [ ] Verify Email endpoint tests
- [ ] Logout endpoint tests

### Estimated Time

2h

### Deadline

12 Nov 2024

### Reviewer

@cemgungor1

**Comment by oguzpancuk** [comment]
This issue is outdated. The new issue for this task is [here](https://github.com/bounswe/bounswe2024group2/issues/484).
