### ISSUE TITLE
[BE] Implement News Ep to Fetch News from RSS Feeds

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#379]
### Description

We plan to fetch news from different RSS feeds in different categories such as financial times, stock market, and cryptocurrency. 

ps: More categories can be added in the future, this issue covers implementation of the technical baseline.

### Required Activities

- [x] Implement logic to fetch news from each corresponding RSS feed
- [x] Implement endpoint for fetching news by entering the news category name

### Estimated Time

1h

### Deadline

12 Nov 2024

### Reviewer

@cemgungor1

**Comment by rukiyeaslan** [comment]
The tasks listed on this issue are completed and can be reviewed from the PR linked to the issue by @cemgungor1.

**Comment by cemgungor1** [comment]
Sorry for the late answer Rukiye. Looks like Halil merged the PR, which is what I would do. Hence I'm also closing this issue.
