### ISSUE TITLE
[BE] Write Tests for News Endpoint

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#381]
### Description

We have implemented an endpoint for fetching news, and tests for this endpoint should be written.

### Required Activities

- [ ] Write unit tests covering all cases

### Estimated Time

30 min

### Deadline

12 Nov 2024

### Reviewer

@cemgungor1

**Comment by rukiyeaslan** [comment]
Tests for news endpoints are implemented in the branch that's attached to this issue. So, issue is up for a review by @cemgungor1.

**Comment by cemgungor1** [comment]
I've checked both unit and integration tests. They are looking fine. Good job Rukiye!
