### ISSUE TITLE
Document user group stories

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#383]
### Description

2 user stories of a group of people should be documented

### Required Activities

- [x] Create Wiki Page
- [x] Create user scenario group 1
- [x] Create user scenario group 2

### Estimated Time

1

### Deadline

13.11.2024

### Reviewer

@danzio19

**Comment by cemgungor1** [comment]
Wiki page is created, and can be access from [here](https://github.com/bounswe/bounswe2024group2/wiki/User-Scenario-Groups)

**Comment by oguzpancuk** [comment]
Scenario 1 is created and added to the [wiki page](https://github.com/bounswe/bounswe2024group2/wiki/User-Scenario-Groups/7ec6e688e5583ff54649ed8f8e8a4765da6f3496)

**Comment by cemgungor1** [comment]
Scenario 2 is created an added to the [wiki page](https://github.com/bounswe/bounswe2024group2/wiki/User-Scenario-Groups/7da0c2e75b7dbd0a9072aaca7c6ea2f725a61e64) 

This issue is done and ready to be reviewed by @danzio19
