### ISSUE TITLE
[FE] Add Loading Indicator For Auth Operations

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#384]
### Description

To enhance user experience our application should give feedback on async loading operations that takes time. By doing so we give our users a much more pleasant experience. To do so we should add indicator loading circle for auth operations on web client

### Required Activities

- [x] Add loading indicator to auth operations

### Estimated Time

4 hours

### Deadline

12 Nov 2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by mahmutbugramert** [comment]
Added spinner as CircleAnimation.js to web. Used it in Login page.  Can be reviewed from linked pr.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Looks good well done. Closing the issue
