### ISSUE TITLE
[MB] Add Dark Mode Toggle

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#386]
### Description

To enhance user experience our application should provide dark mode in mobile client. We should allow users to toggle with a button placed on navbar.

### Required Activities

- [x] Add dark mode toggle to the navbar.
- [x] Add new color set to root.css for dark modes
- [x] Identify components that use hardcoded colors instead of variable ones and correct the usage.

### Estimated Time

4 hours

### Deadline

12 Nov 2024

### Reviewer

@furkansenkal

**Comment by danzio19** [comment]
Added dark mode toggle feature to app.js
Updated index.css to include dark mode colors
Identified and fixed hard coded css colors in pages.
It can be reviewed from [here](https://github.com/bounswe/bounswe2024group2/tree/lab/6-ux-enhancement)

**Comment by m-erkam** [comment]
Issue can be reviewed by @furkansenkal

**Comment by furkansenkal** [comment]
I reviewed your work and it looks good, well done.
