### ISSUE TITLE
[MB] Add Loading Indicator For Auth Operations

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#387]
### Description

To enhance user experience our application should give feedback on async loading operations that takes time. By doing so we give our users a much more pleasant experience. To do so we should add an indicator loading circle for auth operations on mobile client

### Required Activities

- [x] Add loading indicator to auth operations

### Estimated Time

4 hours

### Deadline

12 Nov 2024

### Reviewer

@m-erkam

**Comment by m-erkam** [comment]
Reviewed and approved, nice
