### ISSUE TITLE
[FE] Integrate Community Section with Backend for Post Retrieval  

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#393]
### **Description**  

This task focuses on integrating the Community Section with the backend API to fetch posts dynamically. Currently, post information is displayed using mock data. Instead, we will retrieve post data directly from the backend, ensuring that the Community Page and Post View components are populated with real data.  

This integration will involve:  
- Replacing mock data with API responses.  
- Editing both the Community Page and Post View components to display data fetched from the backend.  
- Ensuring proper error handling, loading states, and responsiveness.  

### **Required Activities**  
- [x] Replace mock data with API calls to fetch post information from the backend.  
- [x] Update the Community Page to display fetched posts, ensuring proper formatting and responsiveness.  
- [x] Modify the Post View component to show detailed information for selected posts using API data.  
- [x] Implement error handling and loading states for a seamless user experience.  
- [x] Test the integration to confirm functionality and resolve any bugs.  

### **Estimated Time**  
12 hours  

### **Deadline**  
22 Nov 2024  

### **Reviewer**  
@Halil-Ibrahim-Kasapoglu

**Comment by mahmutbugramert** [comment]
Community Page and Post View Page succesfully fetches posts from the backend and displays title, description, and the comments if they exists. I did not notice this issue was also including Post View. So, I opened another issue for it #433. Since the changes merged, issue can be closed after a review @Halil-Ibrahim-Kasapoglu.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Closing this one, everything looks good to me
