### ISSUE TITLE
[FE] Integrate Portfolio Management with Backend  

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#394]
### **Description**  

This task focuses on integrating the Portfolio Management feature with backend services to enable persistent storage and retrieval of user portfolios. Currently, portfolios can be created using modals and mock data. With this integration:  
- Portfolios will be stored in the backend using API calls.  
- Users will be able to see their portfolios on the screen by fetching portfolio data from the backend instead of relying on mock data.  

The task involves updating the portfolio creation flow to send data to the backend and modifying the portfolio display components to dynamically populate information retrieved via API calls.  

#### Addressed Requirements:
- 1.2.2.1 Portfolios should be created by the users by entering purchase price and quantity of stock.
- 1.2.2.2 Portfolios shall include one or more stock.

### **Required Activities**  
- [x] Implement API calls to store portfolios created by users in the backend.  
- [x] Replace mock data in the portfolio display with data fetched from the backend.  
- [x] Ensure that portfolio details are dynamically displayed on the user’s screen.  
- [x] Add error handling for failed API calls and loading states for a better user experience.  
- [x] Test the integration for smooth operation and resolve any potential bugs.  

### **Estimated Time**  
12 hours  

### **Deadline**  
25 Nov 2024  

### **Reviewer**  
@mahmutbugramert

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have created a PR related to this. I am kindy asking for your rev @mahmutbugramert. Once the pr is merged I think we can close this issue.

**Comment by mahmutbugramert** [comment]
Since the PR is merged I am closng the issue. Thanks'
