### ISSUE TITLE
[FE] Fetch News Data from Backend and Enhance News Display  

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#395]
### **Description**  

This task involves integrating the frontend with the backend API to fetch real news data instead of using mock data. The News Section will display a limited number of news items by default for each category, with an option for users to view all news if desired. Additionally, testing the integration may reveal the need to propose new RSS fields to improve functionality.  

This feature will enhance the user experience by dynamically displaying news and providing an option to load more content based on user preference.  

### **Required Activities**  
- [x] Replace mock data in the News Section with API calls to fetch real news data from the backend.  
- [x] Implement a feature to display a limited number of news items per category by default.  
- [x] Add a "View All" button to allow users to load and display all news items in each category.  
- [x] Test the fetched data and propose new RSS fields to the backend team if needed.  
- [x] Add error handling for failed API requests and loading states for better user experience.  
- [x] Ensure responsiveness and consistency with the application's UI theme.  

### **Estimated Time**  
10 hours  

### **Deadline**  
26 Nov 2024  

### **Reviewer**  
@mahmutbugramert

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
It is ready to be closed since PR has been merged. Up for final rev @mahmutbugramert

**Comment by mahmutbugramert** [comment]
News page looks great! I am closing the issue since all work done.
