### ISSUE TITLE
[FE] Integrate loglevel Logger for Unified Frontend Logging

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#396]
### **Description**  

This task involves integrating the `loglevel` library into the frontend to establish a centralized logging system. The `loglevel` logger will replace scattered `console.log` statements, providing a unified and configurable way to manage log levels across the application.  

This feature will enhance debugging and maintain clean and professional logging in both development and production environments.  

### **Required Activities**  

- [x] Install the `loglevel` library in the project.  
- [x] Create a reusable `logger.js` utility file under the `src/utils/` directory.  
- [x] Configure log levels:  
- [x] Replace existing `console.log` statements in components with the `loglevel` logger.  
- [x] Ensure all logs include appropriate log levels (`info`, `warn`, `error`, `debug`) for clarity.  

### **Estimated Time**  
5 hours  

### **Deadline**  
26 Nov 2024  

### **Reviewer**  
@mahmutbugramert

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Since the pr is approved and merged I am closing this issue after your final rev @mahmutbugramert

**Comment by mahmutbugramert** [comment]
It looks fine and already merged. Hereby, I am closing the issue.
