### ISSUE TITLE
[MB] Initialize Markets Page 

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#398]
### Description

 The markets page should be created and it needs to contain

- Two tabs for Turkish (Bist) and American (S&P) markets
- Lists of markets with market prices and percentage of price change

### Required Activities

- [x] Initalize page with two market tabs
- [x] Create lists of markets for these tabs

### Estimated Time

3

### Deadline

21 November 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
The page is initialized for bist and s&p markets, changes are visible in the [feature/MB-markets](https://github.com/bounswe/bounswe2024group2/tree/feature/MB-markets) branch. Issue can be reviewed by @furkansenkal

**Comment by furkansenkal** [comment]
I reviewed your work. Markets page is working without error. Well done.
