### ISSUE TITLE
Add Meeting Notes 3

### ISSUE THREAD

**Issue by yasinbastug** [bounswe/bounswe2024group2#40]
### Meeting Details

- Meeting 3
- Date: 03.03.2024
- Note Taker: @yasinbastug 
- Platform: Discord

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [ ] Wiki page initialized
- [x] Notes documented
- [ ] Wiki page is accessible via the sidebar

**Comment by iremnuy** [comment]
Rearranged the notes and converted to wiki format, added them to side bar and home page, so [c'est fini](https://github.com/bounswe/bounswe2024group2/wiki/Meeting-3-(03.03.2024))
