### ISSUE TITLE
Choose and Plan a Data Population Strategy

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2024group2#401]
### Description

- [x] Choose a data population strategy
- [x] Plan the strategy and document how to use it

### Estimated Time

2

### Deadline

19.11.2024

### Reviewer

@cemgungor1

**Comment by oguzpancuk** [comment]
We've decided to use [Faker](https://faker.readthedocs.io/en/master/) to generate and populate data into our system. 

Here's a plan of how to use it:

1. Define data requirements
    1. Identify the models needing dummy data and determine the relationships and constraints: (Currency, Stock, Tag, Portfolio, Post, Comment)
    2. Decide on the number of entries for each model
2. Create a new python file populate.py to write the population script
3. Modify the Docker Configuration
    1. Add latest version of Faker to requirements.txt for installation
    2. Modify the docker-compose.yml file to automate the data population during the container's startup phase. 
```
command: >  
sh -c " 
 python manage.py migrate &&  
 python manage.py shell < bounswe2024group2/backend/populate.py && 
  “
```
4. Check populate.py to ensure foreign keys are handled properly for relationships and constraints
5. Build and run the Docker Containers

**Comment by cemgungor1** [comment]
This looks like a good plan. Good job Oguz. I'm closing this issue
