### ISSUE TITLE
Plan testing for frontend

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#402]
### Description

As it stated in the Lab7's description, we should create an outline for testing of frontend.

### Required Activities

- [x] Initialize a plan
- [x] Create example tests
- [x] Commit changes made to lab branch

### Estimated Time

2 hours

### Deadline

19.11.2024

### Reviewer

@m-erkam

**Comment by mahmutbugramert** [comment]
We decided to use Jest for testing. Created two tests for different pages and committed them. You can see the commits from [this](https://github.com/bounswe/bounswe2024group2/pull/399) PR.

**Comment by mahmutbugramert** [comment]
Issue is open to review @m-erkam.

**Comment by m-erkam** [comment]
Test are created with jest and they look fine. Nice job!
