### ISSUE TITLE
Plan Testing for Mobile

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#403]
### Description

To test our mobile application, we have to decide which testing framework to use and plan which testing methods to use. For the lab session, some test should be implemented.

### Required Activities

- [x] Decide on testing framework
- [x] Create tests for mobile app

### Estimated Time

2

### Deadline

19 November 2024

### Reviewer

@mahmutbugramert

**Comment by m-erkam** [comment]
We have decided on Jest framework and created and committed some of tests for the lab session. Issue can be reviewed.

**Comment by mahmutbugramert** [comment]
Jest is a great choice! Since a tool choosed and inital implementation done, I am closing this issue.
