### ISSUE TITLE
[MB] Initialize Community Page

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#405]
### Description

Community page for our mobile app should be initialized wtih these components:

- Lists of posts which contains the text, buttons for reactions
- Attachments of posts as graph, portfolio or news

### Required Activities

- [x] Initialize the community page with lists of posts
- [x] Implement the attachments to posts with appropriate placement

### Estimated Time

4

### Deadline

23 November 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Community page is initialized with asked features, can be reviewed by @furkansenkal

**Comment by furkansenkal** [comment]
I reviewed your work. Community page works without error. Well done!
