### ISSUE TITLE
[MB] Create Post Creation Page 

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#406]
### Description

The post creation functionality  should be added to mobile application providing these features: 

- Creating posts with text, tag and titles
- Connect line charts of stock prices, portfolios and news to posts

### Required Activities

- [x] Create a screen that covers post creation functionality
- [x] Provide users to attach linecharts, portfolios and news to post

### Estimated Time

4

### Deadline

25 November 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Post creation page is created and conencted to the backend, can be reviewed by @furkansenkal

**Comment by furkansenkal** [comment]
I reviewed your work and it looks good. Thank you.
