### ISSUE TITLE
[MB] Create News Page

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#407]
### Description

News page should be created and connected to backend to fetch data from RSS feed.

### Required Activities

- [x] News page is created.
- [x] The page is connected to backend.

### Estimated Time

4

### Deadline

25 Nov 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
The news page is created and connected to backend. You can see the related pr [here](https://github.com/bounswe/bounswe2024group2/pull/417). Issue is open to be reviewed by @m-erkam.

**Comment by m-erkam** [comment]
News page is nicely created and connected to backend. Good job!
