### ISSUE TITLE
[MB] Connect Community Page to Backend

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#408]
### Description

In order to show the posts to users, the page should be retreived from the backend properly.

### Required Activities

- [x] Connect community page to backend

### Estimated Time

3

### Deadline

25 November 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
The page is connected to backend and posts are visualized in mobile, issue can be reviewed by @furkansenkal

**Comment by furkansenkal** [comment]
I reviewed your work and it looks fine. Well done!
