### ISSUE TITLE
[MB] Create User Context 

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#409]
### Description

The user information should be kept in a context in the mobile app, and used easily whenever it is needed.

### Required Activities

- [x] Create user context 
- [x] Use context to create and list posts, and create portfolios

### Estimated Time

2

### Deadline

25 November 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
I created the user context and it is ready to be used. You can see the related pr [here](https://github.com/bounswe/bounswe2024group2/pull/418). Issue is open to be reviewed by @m-erkam.

**Comment by m-erkam** [comment]
User context is now available in mobile app and can be used in different mobile pages
