### ISSUE TITLE
[BE] Implement Dynamic Stock Pricing

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#410]
### Description

Dynamic stock price fetching should be implemented. Prices will be 15 minutes late, which is the standard for all free applications.

### Required Activities

- [x] Fetch dynamic stock prices

### Estimated Time

3

### Deadline

26.11.2024

### Reviewer

@rukiyeaslan

**Comment by rukiyeaslan** [comment]
I merged your PR and everything looks good, well done!
