### ISSUE TITLE
[BE] Implement Stock price range data

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#420]
### Description

To create graphs, stock price range data endpoint should be implemented

### Required Activities

- [x] Implement stock price range data endpoint
- [x] Return different intervals for different date ranges

### Estimated Time

3

### Deadline

27.11.2024 

### Reviewer

@rukiyeaslan

**Comment by rukiyeaslan** [comment]
the pr is merged and issue can be closed, nice job!
