### ISSUE TITLE
Add Meeting Notes 9

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#431]
### Meeting Details

- Meeting 9
- Date: 2 Nov 2024
- Note Taker: @furkansenkal 
- Platform: Jitsi

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Reviewer

@m-erkam

### Deadline

29 Nov 2024

**Comment by furkansenkal** [comment]
Meeting notes documented to the wiki and added to the sidebar. You can find it [here](https://github.com/bounswe/bounswe2024group2/wiki/General-Meeting-%238-(15.11.2024)) and review @m-erkam.

**Comment by m-erkam** [comment]
Meeting notes are nicely added to wikipage, good work!
