### ISSUE TITLE
[FE] Connect Post View Page to Backend

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#433]
### Description
Previously, Post View page was designed. Now, it is time to connect it to backend. Fetch post from database. Display the title, description, and comments if there is any.

### Required Activities

- [x] (Connect it to backend)
- [x] (Try if it works)

### Estimated Time
6 hours

### Deadline
25.11.2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by mahmutbugramert** [comment]
Issue was fixed before via #411. It is open to review @Halil-Ibrahim-Kasapoglu.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Closing this one, everything looks good to me
