### ISSUE TITLE
Update W3C Standards Documentation

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#435]
### Description

W3C standard documentation needs to be updated. The following page needs to be updated.
[Wiki page](https://github.com/bounswe/bounswe2024group2/wiki/W3C%E2%80%90Annotation/9b3b3510370f35f883a3561ad3bf0eb006682224) 

### Required Activities

- [ ] Page will be updated.

### Estimated Time

30m

### Deadline

03.12.2024

### Reviewer

@cemgungor1

**Comment by rukiyeaslan** [comment]
The updated document can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/W3C%E2%80%90Annotation/9135d3225cd7f56f968dc719c12da384101d78a0). This issue is up for a review by @cemgungor1.

**Comment by cemgungor1** [comment]
The checkbox is not filled but I've checked the update and it looks great. Closing this issue
