### ISSUE TITLE
Document Lab Meeting Notes #8

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#441]
### Meeting Details

- Lab Meeting 8
- Date: 03.12.2024
- Note Taker: @mahmutbugramert 
- Platform: classroom

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Reviewer

@danzio

### Deadline

03.12.2024

**Comment by mahmutbugramert** [comment]
I took the meeting notes. Uploaded them to wiki page. Now it is available in wiki sidebar. You can see the notes [here](https://github.com/bounswe/bounswe2024group2/wiki/8th-Lab-Meeting-Report,-03.12.2024). Issue is up to review @danzio19

**Comment by danzio19** [comment]
Everything looks good, well done! Closing the issue.
