### ISSUE TITLE
[BE] Implement Fetch Portfolios by User Endpoint

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#443]
### Description

An endpoint that fetches portfolios given a user_jd will be implemented.

### Required Activities

- [x] Endpoint is implemented
- [x] Endpoint is documented on swagger

### Estimated Time

1h

### Deadline

10 Dec 2024

### Reviewer

@cemgungor1

**Comment by rukiyeaslan** [comment]
issue is completed and can be reviewed by @cemgungor1

**Comment by cemgungor1** [comment]
Good job Rukiye!
