### ISSUE TITLE
[BE] Implement Fetch Posts by User Endpoint

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#444]
### Description

An endpoint that fetches posts given a user_jd will be implemented.

### Required Activities

- [x] Get endpoint is implemented
- [x] Endpoint is documented on swagger

### Estimated Time

1h

### Deadline

10 Dec 2024

### Reviewer

@cemgungor1

**Comment by rukiyeaslan** [comment]
this task is implemented [here](https://github.com/bounswe/bounswe2024group2/pull/468) and can be reviewed by @cemgungor1.

**Comment by cemgungor1** [comment]
Well done Rukiye, lgtm
