### ISSUE TITLE
[BE] Implement Fetch Comments for Post Endpoint

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#445]
### Description

An endpoint which returns comments of a post will be implemented.

### Required Activities

- [x] Get endpoint is implemented
- [x] Endpoint is documented on swagger

### Estimated Time

1h

### Deadline

10 Dec 2024

### Reviewer

@cemgungor1

**Comment by cemgungor1** [comment]
PR is merged, well implemented
