### ISSUE TITLE
[FE] Implement connection of comments with Backend

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#446]
### Description

This issue aims to implement connection of posts' comments with backend. After completion of #445, assignee of this issue will start to implementation. With this implementation, Registered users shall be able to share their comments on posts. The system shall be able to list comments related to a post.

### Required Activities

- [x] Connect backend
- [x] Test if it works

### Estimated Time

3 hours

### Deadline

14.12.2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by mahmutbugramert** [comment]
With #482 this issue is solved. Open to review @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Well done closing this one.
