### ISSUE TITLE
[FE] Implement tags for web

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#448]
### Description

This issue aims to implement tags for web page. Tags should be get from backend in post creation page. Registered users shall be able to select these tags. Any user viewing posts should be able to view selected tags in posts.

### Required Activities

- [x] Fetch tags from backend
- [x] Make sure can select tags
- [x] View selected tags in posts

### Estimated Time

6 hours

### Deadline

12.12.2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by mahmutbugramert** [comment]
All required activities are done and a PR(#453) opned. Open to review @Halil-Ibrahim-Kasapoglu.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Closing this one after merge of the pr
