### ISSUE TITLE
[BE] Update database with stocks and supported currencies daily

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#449]
### Description

Commands, which will be triggered on each build, should be created to create and/or update database tables: currency and stocks with supported currency and stocks

### Required Activities

- [x] Currencies are put to database: USD & TRY
- [x] Supported Turkish stocks are inserted to database

### Estimated Time

3

### Deadline

12.12.2024

### Reviewer

@rukiyeaslan

**Comment by cemgungor1** [comment]
This issue is done and is ready to be reviewed by @rukiyeaslan

**Comment by rukiyeaslan** [comment]
The issue is completed nicely good job!
