### ISSUE TITLE
[BE] Stock Indices Endpoints

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#450]
### Description

Stock indices database and its relevant endpoints should be created. 

### Required Activities

- [x] Endpoints are created 
- [x] Get request returns prices of the stocks in the index

### Estimated Time

4

### Deadline

12.12.2024

### Reviewer

@rukiyeaslan

**Comment by cemgungor1** [comment]
This issue is now done and ready to be reviewed by @rukiyeaslan

**Comment by rukiyeaslan** [comment]
I checked the endpoints on swagger and they work well, good job!
