### ISSUE TITLE
[FE] Implement usernames and dates on posts.

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#452]
### Description

This issue aims to show author's username and date of the posts on both community page and post view page. Users should be able to see who shared the post and when.

### Required Activities

- [x] Implement username
- [x] Implement date
- [x] Check if they are working

### Estimated Time

3 hours

### Deadline

12.12.2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by mahmutbugramert** [comment]
All required activites are done and a PR(#453 ) opened. Open to review @Halil-Ibrahim-Kasapoglu.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Closing this one after merge of the pr
