### ISSUE TITLE
[MB] Create a Configuration File to Manage Environment-Specific Variables

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#454]
### Description

Currently, the project has several variables hardcoded in multiple files accross the codebase. This approach makes the codebase less maintable and managable. To improve the project structure, the configuration file that abstract these variables should be created .

### Required Activities

- [x] Identify all environment-specific variables in the codebase.
- [x] Create a config.js file to store these variables.

### Estimated Time

2

### Deadline

20 December 2025

### Reviewer

@furkansenkal

**Comment by furkansenkal** [comment]
I reviewed your work and it looks fine. Well done.
