### ISSUE TITLE
[MB] Implement Tag Creation and Use Functionalities

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#455]
### Description

The application needs to have tags as specified in the requirements with these functionalities:

- assignable to posts
- usable to filter the posts by the users. 

### Required Activities

- [x] Design necessary models in the related pages
- [x] Make tags linkable to posts
- [x] Connect the features to the backend

### Estimated Time

3

### Deadline

10 December 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Tags are now can be created and added to posts, issue can be reviewed by @furkansenkal

**Comment by furkansenkal** [comment]
I reviewed your work, users can successfully create and add tags to posts right now. Well done!
