### ISSUE TITLE
[FE] Implement connection of like/unlike with Backend

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#481]
### Description

This issue aims to implement connection of posts' like/unlike with backend. With this implementation, Registered users shall be able to like and unlike posts. 

### Required Activities

- [x] Connect backend
- [x] Test if it works

### Estimated Time

4 hours

### Deadline

14.12.2024

### Reviewer

@Halil-Ibrahim-Kasapoglu

**Comment by mahmutbugramert** [comment]
With #482 this issue is solved. Open to review @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Well done . Closing this one
