### ISSUE TITLE
[BE] Implement Onboarding Unit Tests

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2024group2#484]
### Description

Implement the unit tests for all endpoints.

### Required Activities

- [x] Onboarding unit tests are implemented.
- [x] Unit tests are passed 

### Estimated Time

5

### Deadline

14.12.2024

### Reviewer

@rukiyeaslan

**Comment by rukiyeaslan** [comment]
I reviewed and approved the PR, nice work!
