### ISSUE TITLE
[BE] Update database with Indices

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#485]
### Description

All indices such as Bist100(XU100) should be put to database and updated regularly

### Required Activities

- [x] Indices should be put to database

### Estimated Time

3

### Deadline

18.12.2024

### Reviewer

@oguzpancuk

**Comment by cemgungor1** [comment]
This issue is done. It's PR is [https://github.com/bounswe/bounswe2024group2/pull/528](here). Up to review by @oguzpancuk

**Comment by oguzpancuk** [comment]
Review is done. Good work!
