### ISSUE TITLE
[BE] Stock Information Detail

### ISSUE THREAD

**Issue by cemgungor1** [bounswe/bounswe2024group2#487]
### Description

Stock detail should be returned when a get request is sent.

### Required Activities

- [x] Api calls should be restructured
- [x] Details should be returned

### Estimated Time

2

### Deadline

18.12.2024

### Reviewer

@oguzpancuk

**Comment by cemgungor1** [comment]
This issue is now done and up to review by @oguzpancuk. Related pr can be found [here](https://github.com/bounswe/bounswe2024group2/pull/503)

**Comment by oguzpancuk** [comment]
Review is done. Good work!
