### ISSUE TITLE
[BE] Implement Post Search With Multiple Tags

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2024group2#491]
### Description

Implement an endpoint to search posts with a tag list parameter.

### Required Activities

- [X] Endpoint is implemented
- [X] Endpoint is listed on swagger

### Estimated Time

2

### Deadline

15.12.2024

### Reviewer

@rukiyeaslan

**Comment by rukiyeaslan** [comment]
I reviewed and approved the related PR, good job!
