### ISSUE TITLE
[MB] Implement Like Functionality of Posts

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#501]
### Description

As indicated in the requirements, the posts can be liked to improve user experience in the application.

### Required Activities

- [x] Like functionality is implemented in mobile
- [x] It is connected to backend

### Estimated Time

2

### Deadline

17 December 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Like functionality is implemented and can be accessible via community and posts pages, issue can be reviewed

**Comment by furkansenkal** [comment]
I reviewed the like functionality. Users are now able to like and unlike posts. Thank you.
