### ISSUE TITLE
[MB] Implement Comment Functionality of Posts 

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#502]
### Description

As indicated in the requirements, the posts can be commented to improve forum experience and communication between users in the application.

### Required Activities

- [x] Comment functionality is implemented in mobile
- [x] It is connected to backend

### Estimated Time

2

### Deadline

17 December 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Posts can be commented via post page and comments can be seen in there, issue can be reviewed

**Comment by furkansenkal** [comment]
I reviewed the comment functionality and it works. Well done.
