### ISSUE TITLE
[BE] Create Annotation Project

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#509]
### Description

Annotation project in the backend should be implemented separately.

### Required Activities

- [x]  Start a new django project.

### Estimated Time

30m

### Deadline

17 Dec 2024

### Reviewer

@oguzpancuk

**Comment by rukiyeaslan** [comment]
this issue can be reviewed by @oguzpancuk

**Comment by oguzpancuk** [comment]
Review is done. Good work!
