### ISSUE TITLE
[BE] Configure Annotation Database

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#511]
### Description

Annotation project should have its own db and configurations

### Required Activities

- [x] Configure db environment on docker
- [x] Connect Annotation project to its db

### Estimated Time

30m

### Deadline

17 Dec 2024

### Reviewer

@oguzpancuk

**Comment by rukiyeaslan** [comment]
this issue can be reviewed by @oguzpancuk

**Comment by oguzpancuk** [comment]
Review is done. Good work!
