### ISSUE TITLE
[BE] Implement Annotation Endpoints

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#512]
### Description

REST Endpoints for creating and retrieving annotations should be implemented.

### Required Activities

- [x] Annotation project should communicate with backend project.
- [x] Post endpoint to create annotation
- [x] Get endpoint to get annotations of a post

### Estimated Time

1h

### Deadline

17 Dec 2024

### Reviewer

@oguzpancuk

**Comment by rukiyeaslan** [comment]
this issue can be reviewed by @oguzpancuk

**Comment by oguzpancuk** [comment]
Review is done. Good work!
