### ISSUE TITLE
[MB] Implement Stock Graphic Connection to Posts

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#517]
### Description

In our application, users can give stocks to their posts and sotckprices of linecharts of the given stocks should be visible on the post page.

### Required Activities

- [x] Implement stock connection feature to stocks 
- [x] Design clear appearance of price linecharts of stocks

### Estimated Time

4

### Deadline

17 December 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Users can be able to link stocks to posts and linecharts of the values of stocks can be viewed on the posts page, issue can be reviewed

**Comment by furkansenkal** [comment]
I reviewed the added feature and it works succesfully. Thank you for your work.
