### ISSUE TITLE
[MB] Create Unit Tests for Mobile

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#525]
### Description

Unit tests for each functionality in the mobile pages should be implemented using Jest framework.
Tests should include pages:
- Community
- Create post
- Post
- Home

### Required Activities

- [x] Implement unit tests for mobile application.

### Estimated Time

3

### Deadline

17 December 2024

### Reviewer

@furkansenkal

**Comment by m-erkam** [comment]
Unit tests for community, create post and post pages are created, issue can be reviewed

**Comment by furkansenkal** [comment]
I reviewed your work and the test are working without an error. Well done!
