### ISSUE TITLE
[BE] Add New RSS Feeds for News

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#526]
### Description

New RSS feeds should be added in the news endpoint.

### Required Activities

- [x] Find new RSS feeds
- [x] Parse new RSS feeds such that it returns necessary fields

### Estimated Time

1h

### Deadline

17 Dec 2024

### Reviewer

@cemgungor1

**Comment by rukiyeaslan** [comment]
this issue can be reviewed by @cemgungor1

**Comment by cemgungor1** [comment]
PR is merged and News are working correctly. Well done Rukiye!
