### ISSUE TITLE
[MB] Create New Markets Page

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#537]
### Description

New markets page should be implemented and connected to the backend with the stock details and search.

### Required Activities

- [x] Implemented new markets page

- [x] Connected to backend

- [x] Implemented stock details page

- [x] Implemented search function 

### Estimated Time

6

### Deadline

16 Dec 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
New markets page is implemented with the features mentioned above. Issue is open for a review @m-erkam .

**Comment by m-erkam** [comment]
On the markets page, users can search markets and their details with good design, nice
