### ISSUE TITLE
[MB] Create Portfolio Page

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#538]
### Description

Portfolio and portfolio details pages with creation/deletion/edit features should be implemented and connected to backend.

### Required Activities

- [x] Portfolio page created.
- [x] Create portfolio page created.
- [x] Portfolio details page created.
- [x] Backend functions connected and mentioned features implemented. 

### Estimated Time

7

### Deadline

16 Dec 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
Portfolio feature is fully implemented and ready to use in our mobile app. Issue is open to be reviewed by @m-erkam.

**Comment by m-erkam** [comment]
Portfolio pages are fully implemented and can be used in mobile app, good job
