### ISSUE TITLE
[MB] Update News Page

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#552]
### Description

We should update news page to fetch new RSS feeds.

### Required Activities

- [x] News page updated.

### Estimated Time

2

### Deadline

16 Dec 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
New RSS feeds added to news page of mobile. Issue is open to be reviewed.

**Comment by m-erkam** [comment]
Users can see different feeds on news page, good work
