### ISSUE TITLE
[MB] Create Unit Tests for Portfolio and Markets 

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#553]
### Description

Unit tests should be created for portfolio and markets pages.

### Required Activities

- [x] Portfolio page test created.
- [x] Markets page test created.
- [x] Stock details page test created.
- [x] Portfolio details page test created.

### Estimated Time

3

### Deadline

16 Dec 2024

### Reviewer

@m-erkam

**Comment by furkansenkal** [comment]
Unit tests for mentioned pages are created. Issue is open to be reviewed by @m-erkam.

**Comment by m-erkam** [comment]
Tests are nicely implemented and works well. Nice!
