### ISSUE TITLE
Create User Manual

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2024group2#561]
### Description

User manual should be created and added to the sidebar

### Required Activities

- [X] Create user manual
- [X] Add user manual to sidebar

### Estimated Time

1

### Deadline

20.12.2024

### Reviewer

@cemgungor1

**Comment by oguzpancuk** [comment]
[User manual](https://github.com/bounswe/bounswe2024group2/wiki/User-Manuall) is created and added to the sidebar.

**Comment by cemgungor1** [comment]
Well documented, great job Oguz!
