### ISSUE TITLE
Document Unit Tests

### ISSUE THREAD

**Issue by oguzpancuk** [bounswe/bounswe2024group2#562]
### Description

Unit tests should be documented and linked under Other Artifacts in sidebar.

### Required Activities

- [X] Backend unit tests are documented and accessible via sidebar
- [x] Frontend unit tests are documented and accessible via sidebar
- [x] Mobile unit tests are documented and accessible via sidebar

### Estimated Time

1

### Deadline

20.12.2024

### Reviewer

@rukiyeaslan

**Comment by rukiyeaslan** [comment]
well done!
