### ISSUE TITLE
Create the Project Plan

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#57]
Create the first version of the project plan using the following [website](https://www.projectlibre.com/) Then, create a corresponding section in the wiki and add the project plan.

- [x] Create the project plan
- [x] Add project plan to wiki

**Reviewer:** @furkansenkal

**Comment by iremnuy** [comment]
I installed the Project Libre and initiated our Gant Chart on my local environment.

**Comment by mahmutbugramert** [comment]
Installed the Project Libre.

**Comment by iremnuy** [comment]
I added the Gant chart link to our project plan wiki page, it is yet need other links and a last review.

**Comment by furkansenkal** [comment]
I reviewed your work and did not find any problem. So, closing this issue. Well done team!
