### ISSUE TITLE
Create the First Draft of the Requirements

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#58]
Write the first draft of the requirements according to the following:

- Users will be able to register and login to the system so that they can make a short post, bookmark or like content. 
- Users will also be able to see those who posted or liked content and follow them.

Tasks to do:
- [x] Decide on the sections
- [x] Write the requirements for each of the sections
- [x] Create wiki page about the requirements

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Created a wiki page for the requirements draft, and placed a link for it at the sidebar under the requirements section. The page is accessible at [here](https://github.com/bounswe/bounswe2024group2/wiki/Requirements-(Draft)). The draft is not populated for now but I have provided an example structure for further development. It contains a glossary section and a requirements section divided into two groups functional and non-functional. It was also important to provide two subsections for user and system requirements so I have created them too.  Under them, there are examples of nested numeration and highlighting options.

The initial revision containing these updates is [here](https://github.com/bounswe/bounswe2024group2/wiki/Requirements-(Draft)/0650aa626359194cdaebaf95639aab0374122d01).

**Comment by rukiyeaslan** [comment]
Updated the draft for requirements with detailed section names and initial requirements. The updated wiki page can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Requirements-(Draft)/84bd5b3fb2bd9d49723d2e78ceba4a42eadf53bb).
This is still a draft and the requirements for each section will later be documented in more detail.
