### ISSUE TITLE
Create Wiki Page for Domain Analysis

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#64]
Create a wiki page for the domain ideas that we discussed.

### Reviewer
@mahmutbugramert 

### Deadline
18 March 2024

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Updated the reviewer information in the description and put the issue in requirements elicitation milestone

**Comment by furkansenkal** [comment]
Created the wiki page for domain analysis. You can see it [here](https://github.com/bounswe/bounswe2024group2/wiki/Domain-Analysis).

**Comment by mahmutbugramert** [comment]
Domain ideas are very well described. Good work!
