### ISSUE TITLE
[Wiki Revision] Update Communication Plan

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#66]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [Communication Plan](https://github.com/bounswe/bounswe2024group2/wiki/Communication-Plan/eaa48113d82e73499c5e7a6f2248ef30e34022ae)

### Required Changes

- Add an extra row for extra meetings besides the weekly one (one example of an extra meeting was meeting 5)
- Check possible typos and make sure to correct them.
- To make it more appealing add icons of platforms
- To make it more appealing add icons for the top row items. ie clock icon for time label.

### Acceptance Criteria

- [x] Changes are made and visible
- [x] Changes are reviewed by the reviewer

### Reviewer

@yasinbastug 

### Deadline

17 March 2024

**Comment by rukiyeaslan** [comment]
Requested checks and changes are made and the updated communication plan can be accessed from [here](https://github.com/bounswe/bounswe2024group2/wiki/%F0%9F%93%9E-Communication-Plan/4e2e541daaf64eb6c4542c74cca6659403658d7e).

Task can be reviewed. @danzio19

**Comment by yasinbastug** [comment]
Reviewed, it looks good.
