### ISSUE TITLE
[Wiki Revision] Update RAM Page

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#67]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [Responsibility Assignment Matrix](https://github.com/bounswe/bounswe2024group2/wiki/Responsibility-Assignment-Matrix/d24f0c8838ebfe72cb861f53a6ec66008b27f57f)

### Required Changes

- Fill the responsibility matrix by following the initial template of it.
- Make sure to add tasks up to the milestone for 17 March
- Define the role and edit the respective section, currently there is a placeholder.
- Check for possible typos and correct them

### Acceptance Criteria

- [x] Changes are made and visible
- [x] Changes are reviewed by the reviewer

### Reviewer

@iremnuy

### Deadline

17 March 2024

**Comment by yasinbastug** [comment]
I updated it, as can be seen [here](https://github.com/bounswe/bounswe2024group2/wiki/Responsibility-Assignment-Matrix)

**Comment by iremnuy** [comment]
I just completed revising the RAM, great work @yasinbastug, we can also add RAM,requirements and gant chart under planning section.Also we need a design section for mockups and further design related tasks but this can wait for some time.

**Comment by yasinbastug** [comment]
Thank you, I am closing the issue.
