### ISSUE TITLE
[Wiki Revision] Update Readme File

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#69]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [Readme.md](https://github.com/bounswe/bounswe2024group2/blob/main/README.md)

### Required Changes

- Add information about the domain of the project 
- Update project status

### Acceptance Criteria

- [x] Changes are made and visible
- [ ] Changes are reviewed by the reviewer

### Reviewer

@mahmutbugramert

### Deadline

17 March 2024

**Comment by m-erkam** [comment]
Information is added about project and selected domain. Project status is updated. A missing link is corrected and some emoji is added.

**Comment by mahmutbugramert** [comment]
Changes are satisfying. Requirements link is fixed by me. Good work!
