### ISSUE TITLE
[Wiki Revision] Update Wiki Home Page

### ISSUE THREAD

**Issue by mahmutbugramert** [bounswe/bounswe2024group2#70]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [Wiki Home Page](https://github.com/bounswe/bounswe2024group2/wiki)

### Required Changes

- Add another section for weekly contributions to Wiki Home page 
- Change meeting notes order in the sidebar to oldest first 
- Update "About Project" section
- Add sections which are in sidebar to the main page
- Make titles more appealing with emojis

### Acceptance Criteria

- [x] Changes are made and visible
- [x] Changes are reviewed by the reviewer

### Reviewer

@m-erkam

### Deadline

17 March 2024

**Comment by mahmutbugramert** [comment]
Order of the meeting notes changed, "About Project" section updated, sections added from sidebar, emojis are used.

**Comment by m-erkam** [comment]
Changes are satisfying. Wiki page is nicely arranged. Good work!
