### ISSUE TITLE
Create mockups for the web application

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#71]
Mockups for the web application should be created  using Figma for the following pages:

- [x] Sign Up
- [x] Sign In
- [x] Main Page
- [x] Profile Page
- [x] Director Page
- [x] Actor/Actress Page

Reviewer
@Halil-Ibrahim-Kasapoglu 

Deadline
18 March 2024

**Comment by rukiyeaslan** [comment]
Web mockups for the pages specified in the issue description are completed and documented  on wiki. You can click [here](https://github.com/bounswe/bounswe2024group2/wiki/%F0%9F%92%BB-Mockups/cc14ffe313382653c5d13f48d851e63b09f27db7) to see the mockups.

@Halil-Ibrahim-Kasapoglu this task can be reviewed.

**Comment by rukiyeaslan** [comment]
Following pages are added to web mockups:

- [x]  Password Reset
- [x]  Password Reset Verification
- [x]  New Password
- [x]  Password Reset Success
- [x]  Password Reset Fail
- [x]  Films Screen
- [x]  Lists Screen
- [x]  Film Details
- [x]  Create Post

The resulting mockups are uploaded to [wiki](https://github.com/bounswe/bounswe2024group2/wiki/%F0%9F%92%BB-Mockups/fd3aaa321315422d9cae44a2822e41d2d10f0d92)

The task is completed and can be reviewed @Halil-Ibrahim-Kasapoglu

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
I have reviewed and it looks good to me, closing the issue.
