### ISSUE TITLE
[Wiki Revision] Update Meeting Notes

### ISSUE THREAD

**Issue by furkansenkal** [bounswe/bounswe2024group2#73]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

-  [1st Meeting](https://github.com/bounswe/bounswe2024group2/wiki/1st-Meeting,19.02.2024)
-  [2nd Meeting](https://github.com/bounswe/bounswe2024group2/wiki/2nd-Meeting,21.02.2024)
-  [3rd Meeting](https://github.com/bounswe/bounswe2024group2/wiki/3rd-Meeting,03.03.2024)
-  [4th Meeting](https://github.com/bounswe/bounswe2024group2/wiki/4th-Meeting,07.03.2024)
-  [5th Meeting](https://github.com/bounswe/bounswe2024group2/wiki/5th-Meeting,10.03.2024)

### Required Changes

- The names of the meeting notes needs to be arranged to be consistent in the side bar and on the pages themselves.
- Notes that do not resemble the template should be made similar to the template.
- Completed action items should be ticked to indicate completion.

### Acceptance Criteria

- [x] Changes are made and visible
- [ ] Changes are reviewed by the reviewer

### Reviewer

@iremnuy

### Deadline

18 March 2024

**Comment by iremnuy** [comment]
Those links provided in the description seem to be invalid now, this can be due to any change in their names while revising, I am now checking the original pages via home page, can you arrange the links @furkansenkal

**Comment by furkansenkal** [comment]
I fixed the problem. It was due to name changes of pages. Thank you for warning. You can complete your review and close this issue if there are not any other problems @iremnuy.

**Comment by iremnuy** [comment]
Thank you, great work !
