### ISSUE TITLE
Write User Requirements to Wiki

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#75]
The wiki page for requirements, includes the draft version of requirements. Update the requirements page with the final **user** requirements. 

Reviewer: @m-erkam 

Deadline: 18 March, 2024

**Comment by rukiyeaslan** [comment]
Added user requirements to the requirements section. The corresponding changes can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Requirements/bbfe72dddc70bf65210aea919ea0a92041ac5a9e).

This task can be reviewed @m-erkam.

**Comment by m-erkam** [comment]
Precise and appropriate user requirements have been written. Good work!
