### ISSUE TITLE
Write Non Functional Requirements to Wiki

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#77]
The wiki page for requirements, includes the draft version of requirements. Update the requirements page with the final **non functional** requirements.

Reviewer: @rukiyeaslan 

Deadline: 18 March, 2024

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Added non-functional requirements to the requirements section. The updated version can be found [here](https://github.com/bounswe/bounswe2024group2/wiki/Requirements/cdf0fd00172f0a75622038f1081fc3e7c5365fcc).

This task can be reviewed @rukiyeaslan

**Comment by rukiyeaslan** [comment]
Reviewed the task and all the non functional requirements are documented successfully. Great job @Halil-Ibrahim-Kasapoglu!

Closing the issue as it is completed.
