### ISSUE TITLE
Revise Past Issues

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#79]
### Description

Before our first milestone, since our repository is also a deliverable we need to check for possible flaws on past issues created and closed. Possible flaws are listed below and the scope of this task covers issues before 18 March 2024.

### Possible Flaws

- [x]  Too long or misused title
- [x]  Lack of description
- [x]  Incorrect/Missing labels
- [x]  Issue Not linked to the project
- [x]  No or wrong assignee
- [x]  Missing project status information
- [x]  Missing closing sentence
- [x]  Missing/Incorrect milestone information
- [x]  Incorrect information provided

### Acceptance Criteria

- [x] Find out issues with flaws
- [x] Fixed the flaws

### Deadline

18 March 2024

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Checked 82 issues. There were many issues that were not linked to the project and missing some labels especially done status. Milestone-related ones are organized under the correct milestone. 
Find out due to the change in the wiki page names some history of communication plan and requirements section gone missing and some related issue links to those revisions are broken. One example was #1. Those links are changed to the oldest possible revision.

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Checked issues and i don't see further problems, closing issue

**Comment by furkansenkal** [comment]
I reviewed your work and there seems to be no problem. Great work.
