### ISSUE TITLE
Create mockups for the mobile application

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#81]
Mockups for the mobile application should be created  using Figma for the following pages:

### Authorization

- [x] Log In
- [x] Sign Up
- [x] Password Reset
- [x] Password Reset Verification
- [x] New Password
- [x] Password Reset Success
- [x] Password Reset Fail

### Content

- [x] Home Screen
- [x] Films Screen
- [x] Lists Screen
- [x] User Profile Screen
- [x] Actor Details
- [x] Director Details
- [x] Film Details
- [x] Film Related Posts Section
- [x] Post Details
- [x] List Details
- [x] Create Post
- [x] Create List

Reviewer
@rukiyeaslan 

Deadline
18 March 2024

**Comment by Halil-Ibrahim-Kasapoglu** [comment]
Mobile mockups for the pages specified in the issue description are completed and documented on the wiki. You can click [here](https://github.com/bounswe/bounswe2024group2/wiki/%F0%9F%92%BB-Mockups/cc14ffe313382653c5d13f48d851e63b09f27db7) to see the mockups.

@rukiyeaslan  this task can be reviewed.

**Comment by rukiyeaslan** [comment]
Mockups for mobile are reviewed and all the tasks specified under this issue are completed successfully. Great job @Halil-Ibrahim-Kasapoglu!

Closing the issue as it is completed.
