### ISSUE TITLE
[Wiki Revision] Update RAM

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#86]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [RAM](https://github.com/bounswe/bounswe2024group2/wiki/Responsibility-Assignment-Matrix)

### Required Changes

- Responsibility Assignment Matrix needs to be updated to have the correct form of a RAM, to clarify and assign roles instead of being a list of effort.

### Acceptance Criteria

- [x] Changes are made and visible
- [x] Changes are reviewed by the reviewer

### Reviewer

@yasinbastug

### Deadline

28 March, 2024

**Comment by yasinbastug** [comment]
Good design and nicely divided work sections. It can be closed.
