### ISSUE TITLE
Create a general issue template

### ISSUE THREAD

**Issue by rukiyeaslan** [bounswe/bounswe2024group2#87]
We need to create a general issue template which covers all the issues that don't have a specific template.

Acceptance Criteria:
- [x] Issue template should be opened
- [x] Issue template must have a reviewer field
- [x] Issue template should be reviewed

Reviewer:
@mahmutbugramert 

Deadline:
28 March, 2024

**Comment by mahmutbugramert** [comment]
Requirements looks satisfied. Reviewer field is added. Well done!
