### ISSUE TITLE
Add Meeting Notes 7

### ISSUE THREAD

**Issue by yasinbastug** [bounswe/bounswe2024group2#88]
### Meeting Details

- Meeting 7
- Date: 21.03.2024
- Note Taker: @mahmutbugramert 
- Platform: Discord

### Description

The meeting, for which details are provided above, has concluded, and meeting notes have been taken down by the note-taker. It is necessary to add them to the respective wiki page and document them there. This page should be displayed in the sidebar for easy access.

### Acceptance Criteria

- [x] Wiki page initialized
- [x] Notes documented
- [x] Wiki page is accessible via the sidebar

### Reviewer

@yasinbastug 

### Deadline

25.03.2024

**Comment by iremnuy** [comment]
@danzio19

**Comment by danzio19** [comment]
This issue is closed since the requirements are done.
