### ISSUE TITLE
Research on Sequence Diagram

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#89]
### Description

There is a need to conduct on research on the listed topics below. There are several materials discovered that needs to be consumed to complete the research.

### Research Topics

- Understand how to create Sequence Diagrams
- Realize do's and dont's
- Check tools to create sequence diagrams and select the most suitable one for our needs.

### Materials to Consume

- Moodle slides
### Tools 
- [PlantUML](https://plantuml.com/)
- [draw.io](https://app.diagrams.net/)
- [Lucidchart](https://www.lucidchart.com/pages/)

### Acceptance Criteria

- [x] Materials are consumed

### Deadline

24 March 2024

**Comment by mahmutbugramert** [comment]
Moodle slides are consumed. Research has done through web. PlantUML is fine for our needs. A document is created. You can see it [here](https://github.com/bounswe/bounswe2024group2/wiki/Sequence-Diagrams).
