### ISSUE TITLE
Research on Class Diagram

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#91]
### Description

There is a need conduct on research on the listed topics below. There are several materials discovered that needs to be consumed to complete the research.

### Research Topics

- Understand how to create Class Diagrams
- Realize do's and dont's
- Check tools to create class diagrams and select the most suitable one for our needs.

### Materials to Consume

- Moodle slides
### Tools 
- [PlantUML](https://plantuml.com/)
- [draw.io](https://app.diagrams.net/)
- [Lucidchart](https://www.lucidchart.com/pages/)

### Acceptance Criteria

- [x] Materials are consumed

### Deadline

23 March 2024

**Comment by rukiyeaslan** [comment]
I read slides on moodle, checked each website listed above, read some documentation, and watched a few videos on how to create a class diagram. After my research, I believe that Lucidchart is better for creating more complex diagrams. As our class diagram will be detailed and probably complex, Lucidhart seems to be the safe and best option.

Here is a [youtube video](https://www.youtube.com/watch?v=6XrL5jXmTwM&ab_channel=LucidSoftware) to learn how to create class diagrams on Lucichart.

**Comment by rukiyeaslan** [comment]
I close this issue as the research is completed and required decision is made.
