### ISSUE TITLE
Plan Class Diagrams

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#93]
It is needed to define classes for class diagrams before creating them. The Assignee of this task should make an analysis of what kind of classes we will have. Provide a list of class diagram names in the comments.

### Reviewer 
@rukiyeaslan   

### Deadline 
25 March 2024

**Comment by m-erkam** [comment]
Research is made about class diagrams and  some useful information can be found [here](https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-class-diagram-tutorial/). 

- To create these diagrams it is needed to specify the classes which should be used in the platform. Film, post, different user types like global user, registered user can be examples of the classes.
- Also, the functions of the classes which means the functionalities that the platform is supposed to perform should be specified.

After determining the classes and functions by the group, these class diagrams can be implemented.

**Comment by rukiyeaslan** [comment]
The research is completed and a list of class diagram names is provided. Good job!
