### ISSUE TITLE
Plan Sequence Diagrams

### ISSUE THREAD

**Issue by Halil-Ibrahim-Kasapoglu** [bounswe/bounswe2024group2#94]
It is needed to define diagram names for sequence diagrams before creating them. The Assignee of this task should make an analysis of what kind of sequence diagrams we will have. Provide a list of sequence diagram names in the comments.

### Reviewer 
@mahmutbugramert  

### Deadline 
25 April 2024

**Comment by yasinbastug** [comment]
# Planning for Drawing the Sequence Diagram Using PlantUML and PlantText.com

## Phase 1: Requirement Analysis and Design Preparation
**Duration:** 1-2 days

### Team Meeting (All Members)
- Review and discuss the project requirements thoroughly.
- Confirm the use of **PlantUML** as the diagramming tool and **PlantText.com** for online collaboration and visualization.
- Identify key system interactions and actors (Guest, User, Admin, System, Database).

### Initial Drafting (Person A)
- Use **PlantText.com** to create an initial rough sketch of the sequence diagram.
- Outline major processes (Signup, Login, User Actions, Admin Actions).
- Share the initial drafts with the team through **PlantText.com** for quick feedback and iteration.

## Phase 2: Detailed Design
**Duration:** 2-3 days

### Component Detailing (Person B)
- Focus on detailing each major process using **PlantUML**:
  - Define exact messages between actors and the system (e.g., "Request to Signup", "Authenticate User").
  - Specify conditions and alternative paths (e.g., Validation success/failure).
- Update the **PlantText.com** diagrams continuously to reflect changes and enhancements.

### Interaction with Database (Person C)
- Detail the database interactions using **PlantUML**:
  - What information is retrieved or stored during each interaction?
  - How does the system handle data verification, creation, or updates?
- Use **PlantText.com** to refine and share database interaction diagrams for review.

## Phase 3: Integration and Review
**Duration:** 1-2 days

### Diagram Integration (Person A)
- Integrate the components and interactions into a unified sequence diagram using **PlantUML**.
- Ensure all parts are correctly linked and represented on **PlantText.com**.

### Peer Review (Person B and C)
- Use **PlantText.com** to review the diagram for accuracy, completeness, and compliance with the requirements.
- Check for logical flow, clarity, and understanding.
- Make necessary revisions based on feedback directly in **PlantText.com**.

## Phase 4: Finalization and Presentation
**Duration:** 1 day

### Final Edits (Person A)
- Incorporate all feedback and make final adjustments using **PlantUML**.
- Prepare the final version of the sequence diagram on **PlantText.com**.

### Documentation and Reporting (Person B)
- Document the sequence diagram process and decisions made during its creation.
- Prepare a brief report or presentation using outputs from **PlantText.com** that outlines the diagram for stakeholders or team review.

### Presentation (All Members)
- Use **PlantText.com** to present the final sequence diagram to the team or stakeholders.
- Explain key interactions, processes, and decisions made throughout the diagramming process.

## Team Roles:
- **Person A**: Leads the integration and finalization phases, ensuring that the overall design meets the initial project requirements and is correctly assembled in **PlantUML**.
- **Person B**: Focuses on detailed design aspects, especially the user interactions and error handling, using **PlantUML**.
- **Person C**: Specializes in database interactions, ensuring data flows are accurately represented and secure in the diagram via **PlantUML**.

**Comment by yasinbastug** [comment]
I initialized a diagram for our project with two different approaches: 
1. with packages and usage of UML 2.0 -> [image](https://planttext.com/api/plantuml/png/XPJ1Rjim38RlUWeYfmreNg1OXZfrjai7536QksOpYL1RyYGgMTv-4YrxZckZEGaczV7_IKPFZgGbtzH2bcGi_FJeA9tV7DfqpAf6QO6Q5DrWLTmSORC2wQ0xYagI_2qTmYfF9uxcMo4s6oZKIViMfAvWrqXLmm6jEgfIaZ8QDXl1LM7zFU7W4VRuXx-HwMz_yK6EbWq-04R80xJIkQknrTSeKbqaOIydOG8mtmROyndBT-Zlimv6WDSgbD7ed0Y9wx60WwnLrGdSe_CrkH5rceM35YXDqzRuD_H9o9h6cCANPQm4uJU3AZ38kciCzsgS_cszxWOKAyVCM-hdHKbuKVfzmkxCMum2up0XAqlZDGcimwX6qdu4YBTuTptSxsiLPtE5dRN6XXMeUAICUp4djJ2_dQQGSDVolaNJwMIUpd6pobucDsxqTQbv8uKPH-FACO3zJGYVU6Hxy2jGv0a7cw_zMCCE84MhR7nkKuSDi35rRbbumXDYD-CPQ0mEkSDy9wrxQtdv-hp_aydAwDdD2auByMeSJNc5lAJ0zE_mRFHHsOQ37I7mFx8F2g-SuwReFP9LcF33tuq1Zv0hrzRobcBH1JyuOnlTXt6j76jSyB77ngHISBIcYG_HaYF6H3CVAsobxlPflkqilY19tiLtAcHhh1RhXB0GJs45ucFx3m00)
2. without packages and database component -> [image](https://planttext.com/api/plantuml/png/bLHDRzim3BtxLn0z32km_e406Pgrw7ReOLZGtHcPYONgmn2b1FdteoHdTMfjG2-sBF7nlKUHlkU88IPhEbJH1_YUYEEqVc4AqtBJM-qwSb77Cznipnp9tW0or6NNhTSL2XiLjNSCwtLND-w-Ja6mWj-QJZ1wZlm5zjfOUHbTliRWPOEu0TeI1ZN0xWn913cqT0tkd8y4GH-6kAeY61GwyCwSuPWPqVN09KiHkjK7bqRu1C_-e5rRwHJp-OsIB6eZGf7vv4D_cokZZoZKKmqcx9LVDBhF8VB0Li2MH9hoRg-3nLouIjFrz3xxKk93XKs8HlA7G3b1laP0fNnoiVWl6__nNezcrZ_aUPFYa1j5NRWRPYummLNwLHNL8myxZw7FUedvJUwihSftmsVkAy2TJ_8i3VAX6ofekOaeskVw2jiAVkRZCUsaumRg6vQMifxrQqtB3SdUMY6I7lrdH3LLEtnn-kIDyIVmKkfGng8Hyp9MOtMoIYdB6CzhMJVcg4Soz9TtUVnD1YlD6geLyukiFrwiBuz_w9waqgK0ryDRO_FiZXJsNdeRZRdGLSsZIGoOu-vu9ANtMaaHvR_HtSievV_O7m00)

**Comment by mahmutbugramert** [comment]
Plan is prepared appropriately. Well done!
