### ISSUE TITLE
[Wiki Revision] Update Glossary of the Requirements

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#96]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [Glossary](https://github.com/bounswe/bounswe2024group2/wiki/Requirements#glossary)

### Required Changes

- Revise necessary glossary items according to the feedbacks from the assistant.

### Acceptance Criteria

- [x] Changes are made and visible
- [x] Changes are reviewed by the reviewer

### Reviewer

@rukiyeaslan

### Deadline

21 April 2024

**Comment by m-erkam** [comment]
Glossary updated according to the revision of the assistant. User types are changed and descriptions are arranged. After the revision by @rukiyeaslan, issue can be closed.

**Comment by rukiyeaslan** [comment]
Requested changes are nicely done so closing the issue. Good Job!
