### ISSUE TITLE
[Wiki Revision] Update User Types of the Requirements

### ISSUE THREAD

**Issue by m-erkam** [bounswe/bounswe2024group2#99]
### Description

We need to update several wiki pages for our project. The pages and required changes are listed below.

### Sections to be Revised

- [User Types](https://github.com/bounswe/bounswe2024group2/wiki/Requirements#112-user-types)

### Required Changes

- Revise necessary requirements and make changes according to the feedbacks of the assistant.

### Acceptance Criteria

- [x] Changes are made and visible
- [ ] Changes are reviewed by the reviewer

### Reviewer

@yasinbastug

### Deadline

21 April 2024

**Comment by m-erkam** [comment]
Missing requirements are added like viewin the contents posted by followed users, duplicate requirements are deleted and requirements about semantic search are added. When revision is made, issue can be closed.

**Comment by yasinbastug** [comment]
Global user is added and it seems complete for semantic seach too. All seems well, good work.
